define("ace/mode/xml_highlight_rules",["require","exports","module","ace/lib/oop","ace/mode/text_highlight_rules"],function(a,m,l){l=a("../lib/oop");a=a("./text_highlight_rules").TextHighlightRules;var f=function(a){this.$rules={start:[{token:"string.cdata.xml",regex:"<\\!\\[CDATA\\[",next:"cdata"},{token:["punctuation.xml-decl.xml","keyword.xml-decl.xml"],regex:"(<\\?)(xml)(?=[\\s])",next:"xml_decl",caseInsensitive:!0},{token:["punctuation.instruction.xml","keyword.instruction.xml"],regex:"(<\\?)([_:a-zA-Z\u00c0-\uffff][-_:.a-zA-Z0-9\u00c0-\uffff]*)",
next:"processing_instruction"},{token:"comment.xml",regex:"<\\!--",next:"comment"},{token:["xml-pe.doctype.xml","xml-pe.doctype.xml"],regex:"(<\\!)(DOCTYPE)(?=[\\s])",next:"doctype",caseInsensitive:!0},{include:"tag"},{token:"text.end-tag-open.xml",regex:"</"},{token:"text.tag-open.xml",regex:"<"},{include:"reference"},{defaultToken:"text.xml"}],xml_decl:[{token:"entity.other.attribute-name.decl-attribute-name.xml",regex:"(?:[_:a-zA-Z\u00c0-\uffff][-_:.a-zA-Z0-9\u00c0-\uffff]*:)?[_:a-zA-Z\u00c0-\uffff][-_:.a-zA-Z0-9\u00c0-\uffff]*"},
{token:"keyword.operator.decl-attribute-equals.xml",regex:"="},{include:"whitespace"},{include:"string"},{token:"punctuation.xml-decl.xml",regex:"\\?>",next:"start"}],processing_instruction:[{token:"punctuation.instruction.xml",regex:"\\?>",next:"start"},{defaultToken:"instruction.xml"}],doctype:[{include:"whitespace"},{include:"string"},{token:"xml-pe.doctype.xml",regex:">",next:"start"},{token:"xml-pe.xml",regex:"[-_a-zA-Z0-9:]+"},{token:"punctuation.int-subset",regex:"\\[",push:"int_subset"}],
int_subset:[{token:"text.xml",regex:"\\s+"},{token:"punctuation.int-subset.xml",regex:"]",next:"pop"},{token:["punctuation.markup-decl.xml","keyword.markup-decl.xml"],regex:"(<\\!)([_:a-zA-Z\u00c0-\uffff][-_:.a-zA-Z0-9\u00c0-\uffff]*)",push:[{token:"text",regex:"\\s+"},{token:"punctuation.markup-decl.xml",regex:">",next:"pop"},{include:"string"}]}],cdata:[{token:"string.cdata.xml",regex:"\\]\\]>",next:"start"},{token:"text.xml",regex:"\\s+"},{token:"text.xml",regex:"(?:[^\\]]|\\](?!\\]>))+"}],comment:[{token:"comment.xml",
regex:"--\x3e",next:"start"},{defaultToken:"comment.xml"}],reference:[{token:"constant.language.escape.reference.xml",regex:"(?:&#[0-9]+;)|(?:&#x[0-9a-fA-F]+;)|(?:&[a-zA-Z0-9_:\\.-]+;)"}],attr_reference:[{token:"constant.language.escape.reference.attribute-value.xml",regex:"(?:&#[0-9]+;)|(?:&#x[0-9a-fA-F]+;)|(?:&[a-zA-Z0-9_:\\.-]+;)"}],tag:[{token:["meta.tag.punctuation.tag-open.xml","meta.tag.punctuation.end-tag-open.xml","meta.tag.tag-name.xml"],regex:"(?:(<)|(</))((?:[_:a-zA-Z\u00c0-\uffff][-_:.a-zA-Z0-9\u00c0-\uffff]*:)?[_:a-zA-Z\u00c0-\uffff][-_:.a-zA-Z0-9\u00c0-\uffff]*)",
next:[{include:"attributes"},{token:"meta.tag.punctuation.tag-close.xml",regex:"/?>",next:"start"}]}],tag_whitespace:[{token:"text.tag-whitespace.xml",regex:"\\s+"}],whitespace:[{token:"text.whitespace.xml",regex:"\\s+"}],string:[{token:"string.xml",regex:"'",push:[{token:"string.xml",regex:"'",next:"pop"},{defaultToken:"string.xml"}]},{token:"string.xml",regex:'"',push:[{token:"string.xml",regex:'"',next:"pop"},{defaultToken:"string.xml"}]}],attributes:[{token:"entity.other.attribute-name.xml",regex:"(?:[_:a-zA-Z\u00c0-\uffff][-_:.a-zA-Z0-9\u00c0-\uffff]*:)?[_:a-zA-Z\u00c0-\uffff][-_:.a-zA-Z0-9\u00c0-\uffff]*"},
{token:"keyword.operator.attribute-equals.xml",regex:"="},{include:"tag_whitespace"},{include:"attribute_value"}],attribute_value:[{token:"string.attribute-value.xml",regex:"'",push:[{token:"string.attribute-value.xml",regex:"'",next:"pop"},{include:"attr_reference"},{defaultToken:"string.attribute-value.xml"}]},{token:"string.attribute-value.xml",regex:'"',push:[{token:"string.attribute-value.xml",regex:'"',next:"pop"},{include:"attr_reference"},{defaultToken:"string.attribute-value.xml"}]}]};this.constructor===
f&&this.normalizeRules()};(function(){this.embedTagRules=function(a,f,b){this.$rules.tag.unshift({token:["meta.tag.punctuation.tag-open.xml","meta.tag."+b+".tag-name.xml"],regex:"(<)("+b+"(?=\\s|>|$))",next:[{include:"attributes"},{token:"meta.tag.punctuation.tag-close.xml",regex:"/?>",next:f+"start"}]});this.$rules[b+"-end"]=[{include:"attributes"},{token:"meta.tag.punctuation.tag-close.xml",regex:"/?>",next:"start",onMatch:function(b,f,e){e.splice(0);return this.token}}];this.embedRules(a,f,[{token:["meta.tag.punctuation.end-tag-open.xml",
"meta.tag."+b+".tag-name.xml"],regex:"(</)("+b+"(?=\\s|>|$))",next:b+"-end"},{token:"string.cdata.xml",regex:"<\\!\\[CDATA\\["},{token:"string.cdata.xml",regex:"\\]\\]>"}])}}).call(a.prototype);l.inherits(f,a);m.XmlHighlightRules=f});
define("ace/mode/behaviour/xml","require exports module ace/lib/oop ace/mode/behaviour ace/token_iterator ace/lib/lang".split(" "),function(a,m,l){function f(b,f){return-1<b.type.lastIndexOf(f+".xml")}l=a("../../lib/oop");var n=a("../behaviour").Behaviour,k=a("../../token_iterator").TokenIterator;a("../../lib/lang");a=function(){this.add("string_dquotes","insertion",function(b,a,g,e,d){if('"'==d||"'"==d){b=e.doc.getTextRange(g.getSelectionRange());if(""!==b&&"'"!==b&&'"'!=b&&g.getWrapBehavioursEnabled())return{text:d+
b+d,selection:!1};b=g.getCursorPosition();g=e.doc.getLine(b.row).substring(b.column,b.column+1);b=new k(e,b.row,b.column);e=b.getCurrentToken();if(g==d&&(f(e,"attribute-value")||f(e,"string")))return{text:"",selection:[1,1]};e||(e=b.stepBackward());if(e){for(;f(e,"tag-whitespace")||f(e,"whitespace");)e=b.stepBackward();b=!g||g.match(/\s/);if(f(e,"attribute-equals")&&(b||">"==g)||f(e,"decl-attribute-equals")&&(b||"?"==g))return{text:d+d,selection:[1,1]}}}});this.add("string_dquotes","deletion",function(b,
f,a,e,d){b=e.doc.getTextRange(d);if(!d.isMultiLine()&&('"'==b||"'"==b)&&e.doc.getLine(d.start.row).substring(d.start.column+1,d.start.column+2)==b)return d.end.column++,d});this.add("autoclosing","insertion",function(b,a,g,e,d){if(">"==d&&(b=g.getCursorPosition(),e=new k(e,b.row,b.column),(a=e.getCurrentToken()||e.stepBackward())&&(f(a,"tag-name")||f(a,"tag-whitespace")||f(a,"attribute-name")||f(a,"attribute-equals")||f(a,"attribute-value"))&&!f(a,"reference.attribute-value"))){if(f(a,"attribute-value")&&
(g=a.value.charAt(0),'"'==g||"'"==g)){d=a.value.charAt(a.value.length-1);var c=e.getCurrentTokenColumn()+a.value.length;if(c>b.column||c==b.column&&g!=d)return}for(;!f(a,"tag-name");)a=e.stepBackward();g=e.getCurrentTokenRow();d=e.getCurrentTokenColumn();if(!f(e.stepBackward(),"end-tag-open")&&(e=a.value,g==b.row&&(e=e.substring(0,b.column-d)),!this.voidElements.hasOwnProperty(e.toLowerCase())))return{text:"></"+e+">",selection:[1,1]}}});this.add("autoindent","insertion",function(b,a,f,e,d){if("\n"==
d&&(b=f.getCursorPosition(),a=e.getLine(b.row),f=new k(e,b.row,b.column),(d=f.getCurrentToken())&&-1!==d.type.indexOf("tag-close")&&"/>"!=d.value)){for(;d&&-1===d.type.indexOf("tag-name");)d=f.stepBackward();if(d){var c=d.value;a=f.getCurrentTokenRow();if((d=f.stepBackward())&&-1===d.type.indexOf("end-tag")&&this.voidElements&&!this.voidElements[c])return b=e.getTokenAt(b.row,b.column+1),a=e.getLine(a),a=this.$getIndent(a),e=a+e.getTabString(),b&&"</"===b.value?{text:"\n"+e+"\n"+a,selection:[1,e.length,
1,e.length]}:{text:"\n"+e}}}})};l.inherits(a,n);m.XmlBehaviour=a});
define("ace/mode/folding/xml","require exports module ace/lib/oop ace/lib/lang ace/range ace/mode/folding/fold_mode ace/token_iterator".split(" "),function(a,m,l){function f(e,d){return-1<e.type.lastIndexOf(d+".xml")}var n=a("../../lib/oop");a("../../lib/lang");var k=a("../../range").Range,b=a("./fold_mode").FoldMode,p=a("../../token_iterator").TokenIterator;a=m.FoldMode=function(e,d){b.call(this);this.voidElements=e||{};this.optionalEndTags=n.mixin({},this.voidElements);d&&n.mixin(this.optionalEndTags,
d)};n.inherits(a,b);var g=function(){this.tagName="";this.selfClosing=this.closing=!1;this.start={row:0,column:0};this.end={row:0,column:0}};(function(){this.getFoldWidget=function(e,d,c){var a=this._getFirstTagInLine(e,c);return a?a.closing||!a.tagName&&a.selfClosing?"markbeginend"==d?"end":"":!a.tagName||a.selfClosing||this.voidElements.hasOwnProperty(a.tagName.toLowerCase())||this._findEndTagInLine(e,c,a.tagName,a.end.column)?"":"start":""};this._getFirstTagInLine=function(e,d){for(var c=e.getTokens(d),
a=new g,b=0;b<c.length;b++){var h=c[b];if(f(h,"tag-open")){a.end.column=a.start.column+h.value.length;a.closing=f(h,"end-tag-open");h=c[++b];if(!h)break;a.tagName=h.value;a.end.column+=h.value.length;for(b++;b<c.length;b++)if(h=c[b],a.end.column+=h.value.length,f(h,"tag-close")){a.selfClosing="/>"==h.value;break}return a}if(f(h,"tag-close"))return a.selfClosing="/>"==h.value,a;a.start.column+=h.value.length}return null};this._findEndTagInLine=function(e,a,c,b){e=e.getTokens(a);for(var g=a=0;g<e.length;g++){var h=
e[g];a+=h.value.length;if(!(a<b)&&f(h,"end-tag-open")&&(h=e[g+1])&&h.value==c)return!0}return!1};this._readTagForward=function(a){var d=a.getCurrentToken();if(!d)return null;var c=new g;do if(f(d,"tag-open"))c.closing=f(d,"end-tag-open"),c.start.row=a.getCurrentTokenRow(),c.start.column=a.getCurrentTokenColumn();else if(f(d,"tag-name"))c.tagName=d.value;else if(f(d,"tag-close"))return c.selfClosing="/>"==d.value,c.end.row=a.getCurrentTokenRow(),c.end.column=a.getCurrentTokenColumn()+d.value.length,
a.stepForward(),c;while(d=a.stepForward());return null};this._readTagBackward=function(a){var d=a.getCurrentToken();if(!d)return null;var c=new g;do{if(f(d,"tag-open"))return c.closing=f(d,"end-tag-open"),c.start.row=a.getCurrentTokenRow(),c.start.column=a.getCurrentTokenColumn(),a.stepBackward(),c;f(d,"tag-name")?c.tagName=d.value:f(d,"tag-close")&&(c.selfClosing="/>"==d.value,c.end.row=a.getCurrentTokenRow(),c.end.column=a.getCurrentTokenColumn()+d.value.length)}while(d=a.stepBackward());return null};
this._pop=function(a,d){for(;a.length;){var c=a[a.length-1];if(d&&c.tagName!=d.tagName)if(this.optionalEndTags.hasOwnProperty(c.tagName))a.pop();else return null;else return a.pop()}};this.getFoldWidgetRange=function(a,d,c){var b=this._getFirstTagInLine(a,c);if(!b)return null;d=[];if(b.closing||b.selfClosing)for(a=new p(a,c,b.end.column),b={row:c,column:b.start.column};c=this._readTagBackward(a);){if(c.selfClosing)if(d.length)continue;else return c.start.column+=c.tagName.length+2,c.end.column-=2,
k.fromPoints(c.start,c.end);if(c.closing)d.push(c);else if(this._pop(d,c),0==d.length)return c.start.column+=c.tagName.length+2,c.start.row==c.end.row&&c.start.column<c.end.column&&(c.start.column=c.end.column),k.fromPoints(c.start,b)}else{a=new p(a,c,b.start.column);var f={row:c,column:b.start.column+b.tagName.length+2};b.start.row==b.end.row&&(f.column=b.end.column);for(;c=this._readTagForward(a);){if(c.selfClosing)if(d.length)continue;else return c.start.column+=c.tagName.length+2,c.end.column-=
2,k.fromPoints(c.start,c.end);if(c.closing){if(this._pop(d,c),0==d.length)return k.fromPoints(f,c.start)}else d.push(c)}}}}).call(a.prototype)});
define("ace/mode/xml","require exports module ace/lib/oop ace/lib/lang ace/mode/text ace/mode/xml_highlight_rules ace/mode/behaviour/xml ace/mode/folding/xml ace/worker/worker_client".split(" "),function(a,m,l){l=a("../lib/oop");var f=a("../lib/lang"),n=a("./text").Mode,k=a("./xml_highlight_rules").XmlHighlightRules,b=a("./behaviour/xml").XmlBehaviour,p=a("./folding/xml").FoldMode,g=a("../worker/worker_client").WorkerClient;a=function(){this.HighlightRules=k;this.$behaviour=new b;this.foldingRules=
new p};l.inherits(a,n);(function(){this.voidElements=f.arrayToMap([]);this.blockComment={start:"\x3c!--",end:"--\x3e"};this.createWorker=function(a){var b=new g(["ace"],"ace/mode/xml_worker","Worker");b.attachToDocument(a.getDocument());b.on("error",function(b){a.setAnnotations(b.data)});b.on("terminate",function(){a.clearAnnotations()});return b};this.$id="ace/mode/xml"}).call(a.prototype);m.Mode=a});
