define("ace/mode/json_highlight_rules",["require","exports","module","ace/lib/oop","ace/mode/text_highlight_rules"],function(d,q,r){r=d("../lib/oop");d=d("./text_highlight_rules").TextHighlightRules;var s=function(){this.$rules={start:[{token:"variable",regex:'["](?:(?:\\\\.)|(?:[^"\\\\]))*?["]\\s*(?=:)'},{token:"string",regex:'"',next:"string"},{token:"constant.numeric",regex:"0[xX][0-9a-fA-F]+\\b"},{token:"constant.numeric",regex:"[+-]?\\d+(?:(?:\\.\\d*)?(?:[eE][+-]?\\d+)?)?\\b"},{token:"constant.language.boolean",
regex:"(?:true|false)\\b"},{token:"invalid.illegal",regex:"['](?:(?:\\\\.)|(?:[^'\\\\]))*?[']"},{token:"invalid.illegal",regex:"\\/\\/.*$"},{token:"paren.lparen",regex:"[[({]"},{token:"paren.rparen",regex:"[\\])}]"},{token:"text",regex:"\\s+"}],string:[{token:"constant.language.escape",regex:/\\(?:x[0-9a-fA-F]{2}|u[0-9a-fA-F]{4}|["\\\/bfnrt])/},{token:"string",regex:'[^"\\\\]+'},{token:"string",regex:'"',next:"start"},{token:"string",regex:"",next:"start"}]}};r.inherits(s,d);q.JsonHighlightRules=
s});
define("ace/mode/matching_brace_outdent",["require","exports","module","ace/range"],function(d,q,r){var s=d("../range").Range;d=function(){};(function(){this.checkOutdent=function(c,d){return/^\s+$/.test(c)?/^\s*\}/.test(d):!1};this.autoOutdent=function(c,d){var l=c.getLine(d).match(/^(\s*\})/);if(!l)return 0;var l=l[1].length,n=c.findMatchingBracket({row:d,column:l});if(!n||n.row==d)return 0;n=this.$getIndent(c.getLine(n.row));c.replace(new s(d,0,d,l-1),n)};this.$getIndent=function(c){return c.match(/^\s*/)[0]}}).call(d.prototype);q.MatchingBraceOutdent=
d});
define("ace/mode/behaviour/cstyle","require exports module ace/lib/oop ace/mode/behaviour ace/token_iterator ace/lib/lang".split(" "),function(d,q,r){r=d("../../lib/oop");var s=d("../behaviour").Behaviour,c=d("../../token_iterator").TokenIterator,u=d("../../lib/lang"),l=["text","paren.rparen","punctuation.operator"],n=["text","paren.rparen","punctuation.operator","comment"],g,m={},p=function(a){var e=-1;a.multiSelect&&(e=a.selection.index,m.rangeCount!=a.multiSelect.rangeCount&&(m={rangeCount:a.multiSelect.rangeCount}));if(m[e])return g=
m[e];g=m[e]={autoInsertedBrackets:0,autoInsertedRow:-1,autoInsertedLineEnd:"",maybeInsertedBrackets:0,maybeInsertedRow:-1,maybeInsertedLineStart:"",maybeInsertedLineEnd:""}},t=function(a,e,b,h){var f=a.end.row-a.start.row;return{text:b+e+h,selection:[0,a.start.column+1,f,a.end.column+(f?0:1)]}},k=function(){this.add("braces","insertion",function(a,e,b,h,f){a=b.getCursorPosition();e=h.doc.getLine(a.row);if("{"==f){p(b);f=b.getSelectionRange();var c=h.doc.getTextRange(f);if(""!==c&&"{"!==c&&b.getWrapBehavioursEnabled())return t(f,
c,"{","}");if(k.isSaneInsertion(b,h)){if(/[\]\}\)]/.test(e[a.column])||b.inMultiSelectMode)return k.recordAutoInsert(b,h,"}"),{text:"{}",selection:[1,1]};k.recordMaybeInsert(b,h,"{");return{text:"{",selection:[1,1]}}}else if("}"==f){if(p(b),c=e.substring(a.column,a.column+1),"}"==c&&null!==h.$findOpeningBracket("}",{column:a.column+1,row:a.row})&&k.isAutoInsertedClosing(a,e,f))return k.popAutoInsertedClosing(),{text:"",selection:[1,1]}}else{if("\n"==f||"\r\n"==f){p(b);b="";k.isMaybeInsertedClosing(a,
e)&&(b=u.stringRepeat("}",g.maybeInsertedBrackets),k.clearMaybeInsertedClosing());c=e.substring(a.column,a.column+1);if("}"===c){a=h.findMatchingBracket({row:a.row,column:a.column+1},"}");if(!a)return null;a=this.$getIndent(h.getLine(a.row))}else if(b)a=this.$getIndent(e);else{k.clearMaybeInsertedClosing();return}h=a+h.getTabString();return{text:"\n"+h+"\n"+a+b,selection:[1,h.length,1,h.length]}}k.clearMaybeInsertedClosing()}});this.add("braces","deletion",function(a,e,b,h,f){a=h.doc.getTextRange(f);
if(!f.isMultiLine()&&"{"==a){p(b);if("}"==h.doc.getLine(f.start.row).substring(f.end.column,f.end.column+1))return f.end.column++,f;g.maybeInsertedBrackets--}});this.add("parens","insertion",function(a,e,b,h,f){if("("==f){p(b);f=b.getSelectionRange();a=h.doc.getTextRange(f);if(""!==a&&b.getWrapBehavioursEnabled())return t(f,a,"(",")");if(k.isSaneInsertion(b,h))return k.recordAutoInsert(b,h,")"),{text:"()",selection:[1,1]}}else if(")"==f&&(p(b),b=b.getCursorPosition(),a=h.doc.getLine(b.row),")"==a.substring(b.column,
b.column+1)&&null!==h.$findOpeningBracket(")",{column:b.column+1,row:b.row})&&k.isAutoInsertedClosing(b,a,f)))return k.popAutoInsertedClosing(),{text:"",selection:[1,1]}});this.add("parens","deletion",function(a,e,b,h,f){a=h.doc.getTextRange(f);if(!f.isMultiLine()&&"("==a&&(p(b),")"==h.doc.getLine(f.start.row).substring(f.start.column+1,f.start.column+2)))return f.end.column++,f});this.add("brackets","insertion",function(a,e,b,h,f){if("["==f){p(b);f=b.getSelectionRange();a=h.doc.getTextRange(f);if(""!==
a&&b.getWrapBehavioursEnabled())return t(f,a,"[","]");if(k.isSaneInsertion(b,h))return k.recordAutoInsert(b,h,"]"),{text:"[]",selection:[1,1]}}else if("]"==f&&(p(b),b=b.getCursorPosition(),a=h.doc.getLine(b.row),"]"==a.substring(b.column,b.column+1)&&null!==h.$findOpeningBracket("]",{column:b.column+1,row:b.row})&&k.isAutoInsertedClosing(b,a,f)))return k.popAutoInsertedClosing(),{text:"",selection:[1,1]}});this.add("brackets","deletion",function(a,e,b,h,f){a=h.doc.getTextRange(f);if(!f.isMultiLine()&&
"["==a&&(p(b),"]"==h.doc.getLine(f.start.row).substring(f.start.column+1,f.start.column+2)))return f.end.column++,f});this.add("string_dquotes","insertion",function(a,e,b,h,f){if('"'==f||"'"==f){p(b);a=b.getSelectionRange();e=h.doc.getTextRange(a);if(""!==e&&"'"!==e&&'"'!=e&&b.getWrapBehavioursEnabled())return t(a,e,f,f);if(!e){e=b.getCursorPosition();a=h.doc.getLine(e.row);b=a.substring(e.column-1,e.column);a=a.substring(e.column,e.column+1);var c=h.getTokenAt(e.row,e.column);e=h.getTokenAt(e.row,
e.column+1);if("\\"==b&&c&&/escape/.test(c.type))return null;c=c&&/string|escape/.test(c.type);e=!e||/string|escape/.test(e.type);if(a==f)h=c!==e;else{if(c&&!e||c&&e)return null;e=h.$mode.tokenRe;e.lastIndex=0;h=e.test(b);e.lastIndex=0;b=e.test(b);if(h||b||a&&!/[\s;,.})\]\\]/.test(a))return null;h=!0}return{text:h?f+f:"",selection:[1,1]}}}});this.add("string_dquotes","deletion",function(a,e,b,c,f){a=c.doc.getTextRange(f);if(!f.isMultiLine()&&('"'==a||"'"==a)&&(p(b),c.doc.getLine(f.start.row).substring(f.start.column+
1,f.start.column+2)==a))return f.end.column++,f})};k.isSaneInsertion=function(a,e){var b=a.getCursorPosition(),h=new c(e,b.row,b.column);if(!this.$matchTokenType(h.getCurrentToken()||"text",l)){var f=new c(e,b.row,b.column+1);if(!this.$matchTokenType(f.getCurrentToken()||"text",l))return!1}h.stepForward();return h.getCurrentTokenRow()!==b.row||this.$matchTokenType(h.getCurrentToken()||"text",n)};k.$matchTokenType=function(a,e){return-1<e.indexOf(a.type||a)};k.recordAutoInsert=function(a,e,b){a=a.getCursorPosition();
e=e.doc.getLine(a.row);this.isAutoInsertedClosing(a,e,g.autoInsertedLineEnd[0])||(g.autoInsertedBrackets=0);g.autoInsertedRow=a.row;g.autoInsertedLineEnd=b+e.substr(a.column);g.autoInsertedBrackets++};k.recordMaybeInsert=function(a,e,b){a=a.getCursorPosition();e=e.doc.getLine(a.row);this.isMaybeInsertedClosing(a,e)||(g.maybeInsertedBrackets=0);g.maybeInsertedRow=a.row;g.maybeInsertedLineStart=e.substr(0,a.column)+b;g.maybeInsertedLineEnd=e.substr(a.column);g.maybeInsertedBrackets++};k.isAutoInsertedClosing=
function(a,e,b){return 0<g.autoInsertedBrackets&&a.row===g.autoInsertedRow&&b===g.autoInsertedLineEnd[0]&&e.substr(a.column)===g.autoInsertedLineEnd};k.isMaybeInsertedClosing=function(a,e){return 0<g.maybeInsertedBrackets&&a.row===g.maybeInsertedRow&&e.substr(a.column)===g.maybeInsertedLineEnd&&e.substr(0,a.column)==g.maybeInsertedLineStart};k.popAutoInsertedClosing=function(){g.autoInsertedLineEnd=g.autoInsertedLineEnd.substr(1);g.autoInsertedBrackets--};k.clearMaybeInsertedClosing=function(){g&&
(g.maybeInsertedBrackets=0,g.maybeInsertedRow=-1)};r.inherits(k,s);q.CstyleBehaviour=k});
define("ace/mode/folding/cstyle","require exports module ace/lib/oop ace/range ace/mode/folding/fold_mode".split(" "),function(d,q,r){r=d("../../lib/oop");var s=d("../../range").Range;d=d("./fold_mode").FoldMode;q=q.FoldMode=function(c){c&&(this.foldingStartMarker=new RegExp(this.foldingStartMarker.source.replace(/\|[^|]*?$/,"|"+c.start)),this.foldingStopMarker=new RegExp(this.foldingStopMarker.source.replace(/\|[^|]*?$/,"|"+c.end)))};r.inherits(q,d);(function(){this.foldingStartMarker=/(\{|\[)[^\}\]]*$|^\s*(\/\*)/;
this.foldingStopMarker=/^[^\[\{]*(\}|\])|^[\s\*]*(\*\/)/;this.singleLineBlockCommentRe=/^\s*(\/\*).*\*\/\s*$/;this.tripleStarBlockCommentRe=/^\s*(\/\*\*\*).*\*\/\s*$/;this.startRegionRe=/^\s*(\/\*|\/\/)#?region\b/;this._getFoldWidgetBase=this.getFoldWidget;this.getFoldWidget=function(c,d,l){var n=c.getLine(l);if(this.singleLineBlockCommentRe.test(n)&&!this.startRegionRe.test(n)&&!this.tripleStarBlockCommentRe.test(n))return"";c=this._getFoldWidgetBase(c,d,l);return!c&&this.startRegionRe.test(n)?"start":
c};this.getFoldWidgetRange=function(c,d,l,n){var g=c.getLine(l);if(this.startRegionRe.test(g))return this.getCommentRegionBlock(c,g,l);var m=g.match(this.foldingStartMarker);if(m){g=m.index;if(m[1])return this.openingBracketBlock(c,m[1],l,g);(m=c.getCommentFoldRange(l,g+m[0].length,1))&&!m.isMultiLine()&&(n?m=this.getSectionRange(c,l):"all"!=d&&(m=null));return m}if("markbegin"!==d&&(m=g.match(this.foldingStopMarker)))return g=m.index+m[0].length,m[1]?this.closingBracketBlock(c,m[1],l,g):c.getCommentFoldRange(l,
g,-1)};this.getSectionRange=function(c,d){for(var l=c.getLine(d),n=l.search(/\S/),g=d,m=l.length,p=d+=1,t=c.getLength();++d<t;)if(l=c.getLine(d),l=l.search(/\S/),-1!==l){if(n>l)break;var k=this.getFoldWidgetRange(c,"all",d);if(k)if(k.start.row<=g)break;else if(k.isMultiLine())d=k.end.row;else if(n==l)break;p=d}return new s(g,m,p,c.getLine(p).length)};this.getCommentRegionBlock=function(c,d,l){for(var n=d.search(/\s*$/),g=c.getLength(),m=l,p=/^\s*(?:\/\*|\/\/|--)#?(end)?region\b/,t=1;++l<g;){d=c.getLine(l);
var k=p.exec(d);if(k&&(k[1]?t--:t++,!t))break}c=l;if(c>m)return new s(m,n,c,d.length)}}).call(q.prototype)});
define("ace/mode/json","require exports module ace/lib/oop ace/mode/text ace/mode/json_highlight_rules ace/mode/matching_brace_outdent ace/mode/behaviour/cstyle ace/mode/folding/cstyle ace/worker/worker_client".split(" "),function(d,q,r){r=d("../lib/oop");var s=d("./text").Mode,c=d("./json_highlight_rules").JsonHighlightRules,u=d("./matching_brace_outdent").MatchingBraceOutdent,l=d("./behaviour/cstyle").CstyleBehaviour,n=d("./folding/cstyle").FoldMode,g=d("../worker/worker_client").WorkerClient;d=
function(){this.HighlightRules=c;this.$outdent=new u;this.$behaviour=new l;this.foldingRules=new n};r.inherits(d,s);(function(){this.getNextLineIndent=function(c,d,g){var k=this.$getIndent(d);"start"==c&&d.match(/^.*[\{\(\[]\s*$/)&&(k+=g);return k};this.checkOutdent=function(c,d,g){return this.$outdent.checkOutdent(d,g)};this.autoOutdent=function(c,d,g){this.$outdent.autoOutdent(d,g)};this.createWorker=function(d){var c=new g(["ace"],"ace/mode/json_worker","JsonWorker");c.attachToDocument(d.getDocument());
c.on("annotate",function(c){d.setAnnotations(c.data)});c.on("terminate",function(){d.clearAnnotations()});return c};this.$id="ace/mode/json"}).call(d.prototype);q.Mode=d});
