define("ace/mode/coffee_highlight_rules",["require","exports","module","ace/lib/oop","ace/mode/text_highlight_rules"],function(a,h,g){function e(){var a=this.createKeywordMapper({keyword:"this|throw|then|try|typeof|super|switch|return|break|by|continue|catch|class|in|instanceof|is|isnt|if|else|extends|for|own|finally|function|while|when|new|no|not|delete|debugger|do|loop|of|off|or|on|unless|until|and|yes","constant.language":"true|false|null|undefined|NaN|Infinity","invalid.illegal":"case|const|default|function|var|void|with|enum|export|implements|interface|let|package|private|protected|public|static|yield|__hasProp|slice|bind|indexOf",
"language.support.class":"Array|Boolean|Date|Function|Number|Object|RegExp|ReferenceError|String|Error|EvalError|InternalError|RangeError|ReferenceError|StopIteration|SyntaxError|TypeError|URIError|ArrayBuffer|Float32Array|Float64Array|Int16Array|Int32Array|Int8Array|Uint16Array|Uint32Array|Uint8Array|Uint8ClampedArray","language.support.function":"Math|JSON|isNaN|isFinite|parseInt|parseFloat|encodeURI|encodeURIComponent|decodeURI|decodeURIComponent|String|","variable.language":"window|arguments|prototype|document"},
"identifier"),f={token:["paren.lparen","variable.parameter","paren.rparen","text","storage.type"],regex:/(?:(\()((?:"[^")]*?"|'[^')]*?'|\/[^\/)]*?\/|[^()\"'\/])*?)(\))(\s*))?([\-=]>)/.source},b=/\\(?:x[0-9a-fA-F]{2}|u[0-9a-fA-F]{4}|[0-2][0-7]{0,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.)/;this.$rules={start:[{token:"constant.numeric",regex:"(?:0x[\\da-fA-F]+|(?:\\d+(?:\\.\\d+)?|\\.\\d+)(?:[eE][+-]?\\d+)?)"},{stateName:"qdoc",token:"string",regex:"'''",next:[{token:"string",regex:"'''",next:"start"},{token:"constant.language.escape",
regex:b},{defaultToken:"string"}]},{stateName:"qqdoc",token:"string",regex:'"""',next:[{token:"string",regex:'"""',next:"start"},{token:"paren.string",regex:"#{",push:"start"},{token:"constant.language.escape",regex:b},{defaultToken:"string"}]},{stateName:"qstring",token:"string",regex:"'",next:[{token:"string",regex:"'",next:"start"},{token:"constant.language.escape",regex:b},{defaultToken:"string"}]},{stateName:"qqstring",token:"string.start",regex:'"',next:[{token:"string.end",regex:'"',next:"start"},
{token:"paren.string",regex:"#{",push:"start"},{token:"constant.language.escape",regex:b},{defaultToken:"string"}]},{stateName:"js",token:"string",regex:"`",next:[{token:"string",regex:"`",next:"start"},{token:"constant.language.escape",regex:b},{defaultToken:"string"}]},{regex:"[{}]",onMatch:function(f,a,b){this.next="";return"{"==f&&b.length?(b.unshift("start",a),"paren"):"}"==f&&b.length&&(b.shift(),this.next=b.shift()||"",-1!=this.next.indexOf("string"))?"paren.string":"paren"}},{token:"string.regex",
regex:"///",next:"heregex"},{token:"string.regex",regex:/(?:\/(?![\s=])[^[\/\n\\]*(?:(?:\\[\s\S]|\[[^\]\n\\]*(?:\\[\s\S][^\]\n\\]*)*])[^[\/\n\\]*)*\/)(?:[imgy]{0,4})(?!\w)/},{token:"comment",regex:"###(?!#)",next:"comment"},{token:"comment",regex:"#.*"},{token:["punctuation.operator","text","identifier"],regex:"(\\.)(\\s*)(case|const|default|function|var|void|with|enum|export|implements|interface|let|package|private|protected|public|static|yield|__hasProp|slice|bind|indexOf)"},{token:"punctuation.operator",
regex:"\\."},{token:"keyword text language.support.class text keyword text language.support.class".split(" "),regex:"(class)(\\s+)([$A-Za-z_\\x7f-\\uffff][$\\w\\x7f-\\uffff]*)(?:(\\s+)(extends)(\\s+)([$A-Za-z_\\x7f-\\uffff][$\\w\\x7f-\\uffff]*))?"},{token:["entity.name.function","text","keyword.operator","text"].concat(f.token),regex:"([$A-Za-z_\\x7f-\\uffff][$\\w\\x7f-\\uffff]*)(\\s*)([=:])(\\s*)"+f.regex},f,{token:"variable",regex:"@(?:[$A-Za-z_\\x7f-\\uffff][$\\w\\x7f-\\uffff]*)?"},{token:a,regex:"[$A-Za-z_\\x7f-\\uffff][$\\w\\x7f-\\uffff]*"},
{token:"punctuation.operator",regex:"\\,|\\."},{token:"storage.type",regex:"[\\-=]>"},{token:"keyword.operator",regex:"(?:[-+*/%<>&|^!?=]=|>>>=?|\\-\\-|\\+\\+|::|&&=|\\|\\|=|<<=|>>=|\\?\\.|\\.{2,3}|[!*+-=><])"},{token:"paren.lparen",regex:"[({[]"},{token:"paren.rparen",regex:"[\\]})]"},{token:"text",regex:"\\s+"}],heregex:[{token:"string.regex",regex:".*?///[imgy]{0,4}",next:"start"},{token:"comment.regex",regex:"\\s+(?:#.*)?"},{token:"string.regex",regex:"\\S+"}],comment:[{token:"comment",regex:"###",
next:"start"},{defaultToken:"comment"}]};this.normalizeRules()}g=a("../lib/oop");a=a("./text_highlight_rules").TextHighlightRules;g.inherits(e,a);h.CoffeeHighlightRules=e});
define("ace/mode/matching_brace_outdent",["require","exports","module","ace/range"],function(a,h,g){var e=a("../range").Range;a=function(){};(function(){this.checkOutdent=function(a,f){return/^\s+$/.test(a)?/^\s*\}/.test(f):!1};this.autoOutdent=function(a,f){var b=a.getLine(f).match(/^(\s*\})/);if(!b)return 0;var b=b[1].length,c=a.findMatchingBracket({row:f,column:b});if(!c||c.row==f)return 0;c=this.$getIndent(a.getLine(c.row));a.replace(new e(f,0,f,b-1),c)};this.$getIndent=function(a){return a.match(/^\s*/)[0]}}).call(a.prototype);
h.MatchingBraceOutdent=a});
define("ace/mode/folding/coffee","require exports module ace/lib/oop ace/mode/folding/fold_mode ace/range".split(" "),function(a,h,g){g=a("../../lib/oop");var e=a("./fold_mode").FoldMode,n=a("../../range").Range;a=h.FoldMode=function(){};g.inherits(a,e);(function(){this.getFoldWidgetRange=function(a,b,c){if(b=this.indentationBlock(a,c))return b;b=/\S/;var d=a.getLine(c),e=d.search(b);if(-1!=e&&"#"==d[e]){for(var e=d.length,g=a.getLength(),k=c,l=c;++c<g;){var d=a.getLine(c),p=d.search(b);if(-1!=p){if("#"!=
d[p])break;l=c}}if(l>k)return a=a.getLine(l).length,new n(k,e,l,a)}};this.getFoldWidget=function(a,b,c){b=a.getLine(c);var d=b.search(/\S/),e=a.getLine(c+1),g=a.getLine(c-1),k=g.search(/\S/),l=e.search(/\S/);if(-1==d)return a.foldWidgets[c-1]=-1!=k&&k<l?"start":"","";if(-1==k){if(d==l&&"#"==b[d]&&"#"==e[d])return a.foldWidgets[c-1]="",a.foldWidgets[c+1]="","start"}else if(k==d&&"#"==b[d]&&"#"==g[d]&&-1==a.getLine(c-2).search(/\S/))return a.foldWidgets[c-1]="start",a.foldWidgets[c+1]="";a.foldWidgets[c-
1]=-1!=k&&k<d?"start":"";return d<l?"start":""}}).call(a.prototype)});
define("ace/mode/coffee","require exports module ace/mode/coffee_highlight_rules ace/mode/matching_brace_outdent ace/mode/folding/coffee ace/range ace/mode/text ace/worker/worker_client ace/lib/oop".split(" "),function(a,h,g){function e(){this.HighlightRules=n;this.$outdent=new f;this.foldingRules=new b}var n=a("./coffee_highlight_rules").CoffeeHighlightRules,f=a("./matching_brace_outdent").MatchingBraceOutdent,b=a("./folding/coffee").FoldMode,c=a("../range").Range;g=a("./text").Mode;var d=a("../worker/worker_client").WorkerClient;
a("../lib/oop").inherits(e,g);(function(){var a=/(?:[({[=:]|[-=]>|\b(?:else|try|(?:swi|ca)tch(?:\s+[$A-Za-z_\x7f-\uffff][$\w\x7f-\uffff]*)?|finally))\s*$|^\s*(else\b\s*)?(?:if|for|while|loop)\b(?!.*\bthen\b)/,b=/^(\s*)#/,e=/^\s*###(?!#)/,f=/^\s*/;this.getNextLineIndent=function(b,c,e){var f=this.$getIndent(c),d=this.getTokenizer().getLineTokens(c,b).tokens;d.length&&"comment"===d[d.length-1].type||"start"!==b||!a.test(c)||(f+=e);return f};this.toggleCommentLines=function(a,d,g,h){console.log("toggle");
for(a=new c(0,0,0,0);g<=h;++g){var m=d.getLine(g);e.test(m)||(m=b.test(m)?m.replace(b,"$1"):m.replace(f,"$&#"),a.end.row=a.start.row=g,a.end.column=m.length+1,d.replace(a,m))}};this.checkOutdent=function(a,b,c){return this.$outdent.checkOutdent(b,c)};this.autoOutdent=function(a,b,c){this.$outdent.autoOutdent(b,c)};this.createWorker=function(a){var b=new d(["ace"],"ace/mode/coffee_worker","Worker");b.attachToDocument(a.getDocument());b.on("annotate",function(b){a.setAnnotations(b.data)});b.on("terminate",
function(){a.clearAnnotations()});return b};this.$id="ace/mode/coffee"}).call(e.prototype);h.Mode=e});
