"no use strict";
(function(b){function k(a,c){for(var f=a,e="";f;){var d=c[f];if("string"==typeof d)return d+e;if(d)return d.location.replace(/\/*$/,"/")+(e||d.main||d.name);if(!1===d)return"";d=f.lastIndexOf("/");if(-1===d)break;e=f.substr(d)+e;f=f.slice(0,d)}return a}if("undefined"==typeof b.window||!b.document)if(!b.require||!b.define){b.console=function(){var a=Array.prototype.slice.call(arguments,0);postMessage({type:"log",data:a})};b.console.error=b.console.warn=b.console.log=b.console.trace=b.console;b.window=
b;b.ace=b;b.onerror=function(a,c,f,e,d){postMessage({type:"error",data:{message:a,data:d.data,file:c,line:f,col:e,stack:d.stack}})};b.normalizeModule=function(a,c){if(-1!==c.indexOf("!")){var f=c.split("!");return b.normalizeModule(a,f[0])+"!"+b.normalizeModule(a,f[1])}if("."==c.charAt(0))for(f=a.split("/").slice(0,-1).join("/"),c=(f?f+"/":"")+c;-1!==c.indexOf(".")&&e!=c;){var e=c;c=c.replace(/^\.\//,"").replace(/\/\.\//,"/").replace(/[^\/]+\/\.\.\//,"")}return c};b.require=function(a,c){c||(c=a,
a=null);if(!c.charAt)throw Error("worker.js require() accepts only (parentId, id) as arguments");c=b.normalizeModule(a,c);var f=b.require.modules[c];if(f)return f.initialized||(f.initialized=!0,f.exports=f.factory().exports),f.exports;if(!b.require.tlns)return console.log("unable to load "+c);f=k(c,b.require.tlns);".js"!=f.slice(-3)&&(f+=".js");b.require.id=c;b.require.modules[c]={};importScripts(f);return b.require(a,c)};b.require.modules={};b.require.tlns={};b.define=function(a,c,f){2==arguments.length?
(f=c,"string"!=typeof a&&(c=a,a=b.require.id)):1==arguments.length&&(f=a,c=[],a=b.require.id);if("function"!=typeof f)b.require.modules[a]={exports:f,initialized:!0};else{c.length||(c=["require","exports","module"]);var e=function(d){return b.require(a,d)};b.require.modules[a]={exports:{},factory:function(){var d=this,a=f.apply(this,c.map(function(c){switch(c){case "require":return e;case "exports":return d.exports;case "module":return d;default:return e(c)}}));a&&(d.exports=a);return d}}}};b.define.amd=
{};require.tlns={};b.initBaseUrls=function(a){for(var c in a)require.tlns[c]=a[c]};b.initSender=function(){var a=b.require("ace/lib/event_emitter").EventEmitter,c=b.require("ace/lib/oop"),f=function(){};(function(){c.implement(this,a);this.callback=function(c,d){postMessage({type:"call",id:d,data:c})};this.emit=function(c,d){postMessage({type:"event",name:c,data:d})}}).call(f.prototype);return new f};var p=b.main=null,h=b.sender=null;b.onmessage=function(a){a=a.data;if(a.event&&h)h._signal(a.event,
a.data);else if(a.command)if(p[a.command])p[a.command].apply(p,a.args);else if(b[a.command])b[a.command].apply(b,a.args);else throw Error("Unknown command:"+a.command);else a.init&&(b.initBaseUrls(a.tlns),require("ace/lib/es5-shim"),h=b.sender=b.initSender(),a=require(a.module)[a.classname],p=b.main=new a(h))}}})(this);
define("ace/lib/oop",["require","exports","module"],function(b,k,p){k.inherits=function(b,a){b.super_=a;b.prototype=Object.create(a.prototype,{constructor:{value:b,enumerable:!1,writable:!0,configurable:!0}})};k.mixin=function(b,a){for(var c in a)b[c]=a[c];return b};k.implement=function(b,a){k.mixin(b,a)}});
define("ace/lib/lang",["require","exports","module"],function(b,k,p){k.last=function(c){return c[c.length-1]};k.stringReverse=function(c){return c.split("").reverse().join("")};k.stringRepeat=function(c,a){for(var e="";0<a;)if(a&1&&(e+=c),a>>=1)c+=c;return e};var h=/^\s\s*/,a=/\s\s*$/;k.stringTrimLeft=function(c){return c.replace(h,"")};k.stringTrimRight=function(c){return c.replace(a,"")};k.copyObject=function(c){var a={},e;for(e in c)a[e]=c[e];return a};k.copyArray=function(c){for(var a=[],e=0,
d=c.length;e<d;e++)a[e]=c[e]&&"object"==typeof c[e]?this.copyObject(c[e]):c[e];return a};k.deepCopy=function f(a){if("object"!==typeof a||!a)return a;var d;if(Array.isArray(a)){d=[];for(var g=0;g<a.length;g++)d[g]=f(a[g]);return d}d=a.constructor;if(d===RegExp)return a;d=d();for(g in a)d[g]=f(a[g]);return d};k.arrayToMap=function(a){for(var e={},d=0;d<a.length;d++)e[a[d]]=1;return e};k.createMap=function(a){var e=Object.create(null),d;for(d in a)e[d]=a[d];return e};k.arrayRemove=function(a,e){for(var d=
0;d<=a.length;d++)e===a[d]&&a.splice(d,1)};k.escapeRegExp=function(a){return a.replace(/([.*+?^${}()|[\]\/\\])/g,"\\$1")};k.escapeHTML=function(a){return a.replace(/&/g,"&#38;").replace(/"/g,"&#34;").replace(/'/g,"&#39;").replace(/</g,"&#60;")};k.getMatchOffsets=function(a,e){var d=[];a.replace(e,function(a){d.push({offset:arguments[arguments.length-2],length:a.length})});return d};k.deferredCall=function(a){var e=null,d=function(){e=null;a()},g=function(a){g.cancel();e=setTimeout(d,a||0);return g};
g.schedule=g;g.call=function(){this.cancel();a();return g};g.cancel=function(){clearTimeout(e);e=null;return g};g.isPending=function(){return e};return g};k.delayedCall=function(a,e){var d=null,g=function(){d=null;a()},b=function(a){null==d&&(d=setTimeout(g,a||e))};b.delay=function(a){d&&clearTimeout(d);d=setTimeout(g,a||e)};b.schedule=b;b.call=function(){this.cancel();a()};b.cancel=function(){d&&clearTimeout(d);d=null};b.isPending=function(){return d};return b}});
define("ace/range",["require","exports","module"],function(b,k,p){var h=function(a,c,f,b){this.start={row:a,column:c};this.end={row:f,column:b}};(function(){this.isEqual=function(a){return this.start.row===a.start.row&&this.end.row===a.end.row&&this.start.column===a.start.column&&this.end.column===a.end.column};this.toString=function(){return"Range: ["+this.start.row+"/"+this.start.column+"] -> ["+this.end.row+"/"+this.end.column+"]"};this.contains=function(a,c){return 0==this.compare(a,c)};this.compareRange=
function(a){var c;c=a.end;a=a.start;c=this.compare(c.row,c.column);if(1==c)return c=this.compare(a.row,a.column),1==c?2:0==c?1:0;if(-1==c)return-2;c=this.compare(a.row,a.column);return-1==c?-1:1==c?42:0};this.comparePoint=function(a){return this.compare(a.row,a.column)};this.containsRange=function(a){return 0==this.comparePoint(a.start)&&0==this.comparePoint(a.end)};this.intersects=function(a){a=this.compareRange(a);return-1==a||0==a||1==a};this.isEnd=function(a,c){return this.end.row==a&&this.end.column==
c};this.isStart=function(a,c){return this.start.row==a&&this.start.column==c};this.setStart=function(a,c){"object"==typeof a?(this.start.column=a.column,this.start.row=a.row):(this.start.row=a,this.start.column=c)};this.setEnd=function(a,c){"object"==typeof a?(this.end.column=a.column,this.end.row=a.row):(this.end.row=a,this.end.column=c)};this.inside=function(a,c){return 0!=this.compare(a,c)||this.isEnd(a,c)||this.isStart(a,c)?!1:!0};this.insideStart=function(a,c){return 0!=this.compare(a,c)||this.isEnd(a,
c)?!1:!0};this.insideEnd=function(a,c){return 0!=this.compare(a,c)||this.isStart(a,c)?!1:!0};this.compare=function(a,c){return this.isMultiLine()||a!==this.start.row?a<this.start.row?-1:a>this.end.row?1:this.start.row===a?c>=this.start.column?0:-1:this.end.row===a?c<=this.end.column?0:1:0:c<this.start.column?-1:c>this.end.column?1:0};this.compareStart=function(a,c){return this.start.row==a&&this.start.column==c?-1:this.compare(a,c)};this.compareEnd=function(a,c){return this.end.row==a&&this.end.column==
c?1:this.compare(a,c)};this.compareInside=function(a,c){return this.end.row==a&&this.end.column==c?1:this.start.row==a&&this.start.column==c?-1:this.compare(a,c)};this.clipRows=function(a,c){if(this.end.row>c)var f={row:c+1,column:0};else this.end.row<a&&(f={row:a,column:0});if(this.start.row>c)var b={row:c+1,column:0};else this.start.row<a&&(b={row:a,column:0});return h.fromPoints(b||this.start,f||this.end)};this.extend=function(a,c){var f=this.compare(a,c);if(0==f)return this;if(-1==f)var b={row:a,
column:c};else var d={row:a,column:c};return h.fromPoints(b||this.start,d||this.end)};this.isEmpty=function(){return this.start.row===this.end.row&&this.start.column===this.end.column};this.isMultiLine=function(){return this.start.row!==this.end.row};this.clone=function(){return h.fromPoints(this.start,this.end)};this.collapseRows=function(){return 0==this.end.column?new h(this.start.row,0,Math.max(this.start.row,this.end.row-1),0):new h(this.start.row,0,this.end.row,0)};this.toScreenRange=function(a){var c=
a.documentToScreenPosition(this.start);a=a.documentToScreenPosition(this.end);return new h(c.row,c.column,a.row,a.column)};this.moveBy=function(a,c){this.start.row+=a;this.start.column+=c;this.end.row+=a;this.end.column+=c}}).call(h.prototype);h.fromPoints=function(a,c){return new h(a.row,a.column,c.row,c.column)};h.comparePoints=function(a,c){return a.row-c.row||a.column-c.column};h.comparePoints=function(a,c){return a.row-c.row||a.column-c.column};k.Range=h});
define("ace/apply_delta",["require","exports","module"],function(b,k,p){k.applyDelta=function(b,a,c){c=a.start.row;var f=a.start.column,e=b[c]||"";switch(a.action){case "insert":if(1===a.lines.length)b[c]=e.substring(0,f)+a.lines[0]+e.substring(f);else{var d=[c,1].concat(a.lines);b.splice.apply(b,d);b[c]=e.substring(0,f)+b[c];b[c+a.lines.length-1]+=e.substring(f)}break;case "remove":d=a.end.column,a=a.end.row,c===a?b[c]=e.substring(0,f)+e.substring(d):b.splice(c,a-c+1,e.substring(0,f)+b[a].substring(d))}}});
define("ace/lib/event_emitter",["require","exports","module"],function(b,k,p){b={};var h=function(){this.propagationStopped=!0},a=function(){this.defaultPrevented=!0};b._emit=b._dispatchEvent=function(c,b){this._eventRegistry||(this._eventRegistry={});this._defaultHandlers||(this._defaultHandlers={});var e=this._eventRegistry[c]||[],d=this._defaultHandlers[c];if(e.length||d){"object"==typeof b&&b||(b={});b.type||(b.type=c);b.stopPropagation||(b.stopPropagation=h);b.preventDefault||(b.preventDefault=
a);for(var e=e.slice(),g=0;g<e.length&&(e[g](b,this),!b.propagationStopped);g++);if(d&&!b.defaultPrevented)return d(b,this)}};b._signal=function(a,b){var e=(this._eventRegistry||{})[a];if(e)for(var e=e.slice(),d=0;d<e.length;d++)e[d](b,this)};b.once=function(a,b){var e=this;b&&this.addEventListener(a,function g(){e.removeEventListener(a,g);b.apply(null,arguments)})};b.setDefaultHandler=function(a,b){var e=this._defaultHandlers;e||(e=this._defaultHandlers={_disabled_:{}});if(e[a]){var d=e[a],g=e._disabled_[a];
g||(e._disabled_[a]=g=[]);g.push(d);d=g.indexOf(b);-1!=d&&g.splice(d,1)}e[a]=b};b.removeDefaultHandler=function(a,b){var e=this._defaultHandlers;if(e){var d=e._disabled_[a];e[a]==b?d&&this.setDefaultHandler(a,d.pop()):d&&(e=d.indexOf(b),-1!=e&&d.splice(e,1))}};b.on=b.addEventListener=function(a,b,e){this._eventRegistry=this._eventRegistry||{};var d=this._eventRegistry[a];d||(d=this._eventRegistry[a]=[]);if(-1==d.indexOf(b))d[e?"unshift":"push"](b);return b};b.off=b.removeListener=b.removeEventListener=
function(a,b){this._eventRegistry=this._eventRegistry||{};var e=this._eventRegistry[a];if(e){var d=e.indexOf(b);-1!==d&&e.splice(d,1)}};b.removeAllListeners=function(a){this._eventRegistry&&(this._eventRegistry[a]=[])};k.EventEmitter=b});
define("ace/anchor",["require","exports","module","ace/lib/oop","ace/lib/event_emitter"],function(b,k,p){var h=b("./lib/oop"),a=b("./lib/event_emitter").EventEmitter;b=k.Anchor=function(a,b,e){this.$onChange=this.onChange.bind(this);this.attach(a);"undefined"==typeof e?this.setPosition(b.row,b.column):this.setPosition(b,e)};(function(){function b(a,c,d){d=d?a.column<=c.column:a.column<c.column;return a.row<c.row||a.row==c.row&&d}h.implement(this,a);this.getPosition=function(){return this.$clipPositionToDocument(this.row,
this.column)};this.getDocument=function(){return this.document};this.$insertRight=!1;this.onChange=function(a){var e,d;if(!(a.start.row==a.end.row&&a.start.row!=this.row||a.start.row>this.row)){d={row:this.row,column:this.column};e=this.$insertRight;var g="insert"==a.action,x=(g?1:-1)*(a.end.row-a.start.row),k=(g?1:-1)*(a.end.column-a.start.column),l=a.start;a=g?l:a.end;b(d,l,e)?(e=d.row,d=d.column):b(a,d,!e)?(e=d.row+x,d=d.column+(d.row==a.row?k:0)):(e=l.row,d=l.column);this.setPosition(e,d,!0)}};
this.setPosition=function(a,b,d){a=d?{row:a,column:b}:this.$clipPositionToDocument(a,b);if(this.row!=a.row||this.column!=a.column)b={row:this.row,column:this.column},this.row=a.row,this.column=a.column,this._signal("change",{old:b,value:a})};this.detach=function(){this.document.removeEventListener("change",this.$onChange)};this.attach=function(a){this.document=a||this.document;this.document.on("change",this.$onChange)};this.$clipPositionToDocument=function(a,b){var d={};a>=this.document.getLength()?
(d.row=Math.max(0,this.document.getLength()-1),d.column=this.document.getLine(d.row).length):0>a?(d.row=0,d.column=0):(d.row=a,d.column=Math.min(this.document.getLine(d.row).length,Math.max(0,b)));0>b&&(d.column=0);return d}}).call(b.prototype)});
define("ace/document","require exports module ace/lib/oop ace/apply_delta ace/lib/event_emitter ace/range ace/anchor".split(" "),function(b,k,p){var h=b("./lib/oop"),a=b("./apply_delta").applyDelta,c=b("./lib/event_emitter").EventEmitter,f=b("./range").Range,e=b("./anchor").Anchor;b=function(d){this.$lines=[""];0===d.length?this.$lines=[""]:Array.isArray(d)?this.insertMergedLines({row:0,column:0},d):this.insert({row:0,column:0},d)};(function(){h.implement(this,c);this.setValue=function(d){var a=this.getLength()-
1;this.remove(new f(0,0,a,this.getLine(a).length));this.insert({row:0,column:0},d)};this.getValue=function(){return this.getAllLines().join(this.getNewLineCharacter())};this.createAnchor=function(d,a){return new e(this,d,a)};0==="aaa".split(/a/).length?this.$split=function(d){return d.replace(/\r\n|\r/g,"\n").split("\n")}:this.$split=function(d){return d.split(/\r\n|\r|\n/)};this.$detectNewLine=function(d){this.$autoNewLine=(d=d.match(/^.*?(\r\n|\r|\n)/m))?d[1]:"\n";this._signal("changeNewLineMode")};
this.getNewLineCharacter=function(){switch(this.$newLineMode){case "windows":return"\r\n";case "unix":return"\n";default:return this.$autoNewLine||"\n"}};this.$autoNewLine="";this.$newLineMode="auto";this.setNewLineMode=function(d){this.$newLineMode!==d&&(this.$newLineMode=d,this._signal("changeNewLineMode"))};this.getNewLineMode=function(){return this.$newLineMode};this.isNewLine=function(d){return"\r\n"==d||"\r"==d||"\n"==d};this.getLine=function(d){return this.$lines[d]||""};this.getLines=function(d,
a){return this.$lines.slice(d,a+1)};this.getAllLines=function(){return this.getLines(0,this.getLength())};this.getLength=function(){return this.$lines.length};this.getTextRange=function(d){return this.getLinesForRange(d).join(this.getNewLineCharacter())};this.getLinesForRange=function(d){var a;if(d.start.row===d.end.row)a=[this.getLine(d.start.row).substring(d.start.column,d.end.column)];else{a=this.getLines(d.start.row,d.end.row);a[0]=(a[0]||"").substring(d.start.column);var b=a.length-1;d.end.row-
d.start.row==b&&(a[b]=a[b].substring(0,d.end.column))}return a};this.insertLines=function(a,b){console.warn("Use of document.insertLines is deprecated. Use the insertFullLines method instead.");return this.insertFullLines(a,b)};this.removeLines=function(a,b){console.warn("Use of document.removeLines is deprecated. Use the removeFullLines method instead.");return this.removeFullLines(a,b)};this.insertNewLine=function(a){console.warn("Use of document.insertNewLine is deprecated. Use insertMergedLines(position, ['', '']) instead.");
return this.insertMergedLines(a,["",""])};this.insert=function(a,b){1>=this.getLength()&&this.$detectNewLine(b);return this.insertMergedLines(a,this.$split(b))};this.insertInLine=function(a,b){var c=this.clippedPos(a.row,a.column),e=this.pos(a.row,a.column+b.length);this.applyDelta({start:c,end:e,action:"insert",lines:[b]},!0);return this.clonePos(e)};this.clippedPos=function(a,b){var c=this.getLength();void 0===a?a=c:0>a?a=0:a>=c&&(a=c-1,b=void 0);c=this.getLine(a);void 0==b&&(b=c.length);b=Math.min(Math.max(b,
0),c.length);return{row:a,column:b}};this.clonePos=function(a){return{row:a.row,column:a.column}};this.pos=function(a,b){return{row:a,column:b}};this.$clipPosition=function(a){var b=this.getLength();a.row>=b?(a.row=Math.max(0,b-1),a.column=this.getLine(b-1).length):(a.row=Math.max(0,a.row),a.column=Math.min(Math.max(a.column,0),this.getLine(a.row).length));return a};this.insertFullLines=function(a,b){a=Math.min(Math.max(a,0),this.getLength());var c=0;a<this.getLength()?(b=b.concat([""]),c=0):(b=[""].concat(b),
a--,c=this.$lines[a].length);this.insertMergedLines({row:a,column:c},b)};this.insertMergedLines=function(a,b){var c=this.clippedPos(a.row,a.column),e={row:c.row+b.length-1,column:(1==b.length?c.column:0)+b[b.length-1].length};this.applyDelta({start:c,end:e,action:"insert",lines:b});return this.clonePos(e)};this.remove=function(a){var b=this.clippedPos(a.start.row,a.start.column);a=this.clippedPos(a.end.row,a.end.column);this.applyDelta({start:b,end:a,action:"remove",lines:this.getLinesForRange({start:b,
end:a})});return this.clonePos(b)};this.removeInLine=function(a,b,c){b=this.clippedPos(a,b);a=this.clippedPos(a,c);this.applyDelta({start:b,end:a,action:"remove",lines:this.getLinesForRange({start:b,end:a})},!0);return this.clonePos(b)};this.removeFullLines=function(a,b){a=Math.min(Math.max(0,a),this.getLength()-1);b=Math.min(Math.max(0,b),this.getLength()-1);var c=b==this.getLength()-1&&0<a,e=b<this.getLength()-1,l=c?a-1:a,c=c?this.getLine(l).length:0,z=e?b+1:b,e=e?0:this.getLine(z).length,l=new f(l,
c,z,e),e=this.$lines.slice(a,b+1);this.applyDelta({start:l.start,end:l.end,action:"remove",lines:this.getLinesForRange(l)});return e};this.removeNewLine=function(a){a<this.getLength()-1&&0<=a&&this.applyDelta({start:this.pos(a,this.getLine(a).length),end:this.pos(a+1,0),action:"remove",lines:["",""]})};this.replace=function(a,b){!a instanceof f&&(a=f.fromPoints(a.start,a.end));if(0===b.length&&a.isEmpty())return a.start;if(b==this.getTextRange(a))return a.end;this.remove(a);return b?this.insert(a.start,
b):a.start};this.applyDeltas=function(a){for(var b=0;b<a.length;b++)this.applyDelta(a[b])};this.revertDeltas=function(a){for(var b=a.length-1;0<=b;b--)this.revertDelta(a[b])};this.applyDelta=function(b,c){var e="insert"==b.action;(e?1>=b.lines.length&&!b.lines[0]:!f.comparePoints(b.start,b.end))||(e&&2E4<b.lines.length&&this.$splitAndapplyLargeDelta(b,2E4),a(this.$lines,b,c),this._signal("change",b))};this.$splitAndapplyLargeDelta=function(a,b){var c=a.lines,e=c.length,l=a.start.row,f=a.start.column,
m=0,k=0;do{var m=k,k=k+(b-1),t=c.slice(m,k);if(k>e){a.lines=t;a.start.row=l+m;a.start.column=f;break}t.push("");this.applyDelta({start:this.pos(l+m,f),end:this.pos(l+k,f=0),action:a.action,lines:t},!0)}while(1)};this.revertDelta=function(a){this.applyDelta({start:this.clonePos(a.start),end:this.clonePos(a.end),action:"insert"==a.action?"remove":"insert",lines:a.lines.slice()})};this.indexToPosition=function(a,b){for(var c=this.$lines||this.getAllLines(),e=this.getNewLineCharacter().length,l=b||0,
f=c.length;l<f;l++)if(a-=c[l].length+e,0>a)return{row:l,column:a+c[l].length+e};return{row:f-1,column:c[f-1].length}};this.positionToIndex=function(a,b){for(var c=this.$lines||this.getAllLines(),e=this.getNewLineCharacter().length,l=0,f=Math.min(a.row,c.length),m=b||0;m<f;++m)l+=c[m].length+e;return l+a.column}}).call(b.prototype);k.Document=b});
define("ace/worker/mirror","require exports module ace/range ace/document ace/lib/lang".split(" "),function(b,k,p){b("../range");var h=b("../document").Document,a=b("../lib/lang");b=k.Mirror=function(b){this.sender=b;var f=this.doc=new h(""),e=this.deferredUpdate=a.delayedCall(this.onUpdate.bind(this)),d=this;b.on("change",function(a){a=a.data;if(a[0].start)f.applyDeltas(a);else for(var b=0;b<a.length;b+=2){var c=Array.isArray(a[b+1])?{action:"insert",start:a[b],lines:a[b+1]}:{action:"remove",start:a[b],
end:a[b+1]};f.applyDelta(c,!0)}if(d.$timeout)return e.schedule(d.$timeout);d.onUpdate()})};(function(){this.$timeout=500;this.setTimeout=function(a){this.$timeout=a};this.setValue=function(a){this.doc.setValue(a);this.deferredUpdate.schedule(this.$timeout)};this.getValue=function(a){this.sender.callback(this.doc.getValue(),a)};this.onUpdate=function(){};this.isPending=function(){return this.deferredUpdate.isPending()}}).call(b.prototype)});
define("ace/mode/xml/sax",["require","exports","module"],function(b,k,p){function h(){}function a(a,b,D,m,v){function k(a){var b=a.slice(1,-1);if(b in D)return D[b];if("#"===b.charAt(0))return a=parseInt(b.substr(1).replace("x","0x")),65535<a?(a-=65536,a=String.fromCharCode(55296+(a>>10),56320+(a&1023))):a=String.fromCharCode(a),a;v.error("entity not found:"+a);return a}function h(b){var c=a.substring(A,b).replace(/&#?\w+;/g,k);n&&q(A);m.characters(c,0,b-A);A=b}function q(b,c){for(;b>=C&&(c=y.exec(a));)B=
c.index,C=B+c[0].length,n.lineNumber++;n.columnNumber=b-B+1}var B=0,C=0,y=/.+(?:\r\n?|\n)|.*$/g,n=m.locator;b=[{currentNSMap:b}];for(var Q={},A=0;;){var r=a.indexOf("<",A);if(0>r){if(!a.substr(A).match(/^\s*$/)){var s=m.document,F=s.createTextNode(a.substr(A));s.appendChild(F);m.currentElement=F}break}r>A&&h(r);switch(a.charAt(r+1)){case "/":var s=a.indexOf(">",r+3),K=a.substring(r+2,s),G;if(1<b.length)G=b.pop();else{v.fatalError("end tag name not found for: "+K);break}var x=G.localNSMap;G.tagName!=
K&&v.fatalError("end tag name: "+K+" does not match the current start tagName: "+G.tagName);m.endElement(G.uri,G.localName,K);if(x)for(F in x)m.endPrefixMapping(F);s++;break;case "?":n&&q(r);s=l(a,r,m);break;case "!":n&&q(r);s=E(a,r,m,v);break;default:try{n&&q(r);var p=new z,s=f(a,r,p,k,v),M=p.length;if(M&&n){for(var U=c(n,{}),r=0;r<M;r++){var H=p[r];q(H.offset);H.offset=c(n,{})}c(U,n)}!p.closed&&g(a,s,p.tagName,Q)&&(p.closed=!0,D.nbsp||v.warning("unclosed xml attribute"));e(p,m,b);"http://www.w3.org/1999/xhtml"!==
p.uri||p.closed?s++:s=d(a,s,p.tagName,k,m)}catch(N){v.error("element parse error: "+N),s=-1}}0>s?h(r+1):A=s}}function c(a,b){b.lineNumber=a.lineNumber;b.columnNumber=a.columnNumber;return b}function f(a,b,c,d,e){for(var l,f,m=++b,g=0;;){var k=a.charAt(m);switch(k){case "=":if(1===g)l=a.slice(b,m),g=3;else if(2===g)g=3;else throw Error("attribute equal must after attrName");break;case "'":case '"':if(3===g)if(b=m+1,m=a.indexOf(k,b),0<m)f=a.slice(b,m).replace(/&#?\w+;/g,d),c.add(l,f,b-1),g=5;else throw Error("attribute value no end '"+
k+"' match");else if(4==g)f=a.slice(b,m).replace(/&#?\w+;/g,d),c.add(l,f,b),e.warning('attribute "'+l+'" missed start quot('+k+")!!"),b=m+1,g=5;else throw Error('attribute value must after "="');break;case "/":switch(g){case 0:c.setTagName(a.slice(b,m));case 5:case 6:case 7:g=7,c.closed=!0;case 4:case 1:case 2:break;default:throw Error("attribute invalid close char('/')");}break;case "":e.error("unexpected end of input");case ">":switch(g){case 0:c.setTagName(a.slice(b,m));case 5:case 6:case 7:break;
case 4:case 1:f=a.slice(b,m),"/"===f.slice(-1)&&(c.closed=!0,f=f.slice(0,-1));case 2:2===g&&(f=l);4==g?(e.warning('attribute "'+f+'" missed quot(")!!'),c.add(l,f.replace(/&#?\w+;/g,d),b)):(e.warning('attribute "'+f+'" missed value!! "'+f+'" instead!!'),c.add(f,f,b));break;case 3:throw Error("attribute value missed!!");}return m;case "\u0080":k=" ";default:if(" ">=k)switch(g){case 0:c.setTagName(a.slice(b,m));g=6;break;case 1:l=a.slice(b,m);g=2;break;case 4:f=a.slice(b,m).replace(/&#?\w+;/g,d),e.warning('attribute "'+
f+'" missed quot(")!!'),c.add(l,f,b);case 5:g=6}else switch(g){case 2:e.warning('attribute "'+l+'" missed value!! "'+l+'" instead!!');c.add(l,l,b);b=m;g=1;break;case 5:e.warning('attribute space is required"'+l+'"!!');case 6:g=1;b=m;break;case 3:g=4;b=m;break;case 7:throw Error("elements closed character '/' and '>' must be connected to");}}m++}}function e(a,b,c){for(var d=a.tagName,e=null,f=c[c.length-1].currentNSMap,l=a.length;l--;){var m=a[l],g=m.qName,k=m.value,h=g.indexOf(":");if(0<h)var n=m.prefix=
g.slice(0,h),h=g.slice(h+1),n="xmlns"===n&&h;else h=g,n="xmlns"===g&&"";m.localName=h;!1!==n&&(null==e&&(e={},x(f,f={})),f[n]=e[n]=k,m.uri="http://www.w3.org/2000/xmlns/",b.startPrefixMapping(n,k))}for(l=a.length;l--;)if(m=a[l],n=m.prefix)"xml"===n&&(m.uri="http://www.w3.org/XML/1998/namespace"),"xmlns"!==n&&(m.uri=f[n]);h=d.indexOf(":");0<h?(n=a.prefix=d.slice(0,h),h=a.localName=d.slice(h+1)):(n=null,h=a.localName=d);l=a.uri=f[n||""];b.startElement(l,h,d,a);if(a.closed){if(b.endElement(l,h,d),e)for(n in e)b.endPrefixMapping(n)}else a.currentNSMap=
f,a.localNSMap=e,c.push(a)}function d(a,b,c,d,e){if(/^(?:script|textarea)$/i.test(c)){var l=a.indexOf("</"+c+">",b);a=a.substring(b+1,l);if(/[&<]/.test(a)){if(/^script$/i.test(c))return e.characters(a,0,a.length),l;a=a.replace(/&#?\w+;/g,d);e.characters(a,0,a.length);return l}}return b+1}function g(a,b,c,d){var e=d[c];null==e&&(e=d[c]=a.lastIndexOf("</"+c+">"));return e<b}function x(a,b){for(var c in a)b[c]=a[c]}function E(a,b,c,d){switch(a.charAt(b+2)){case "-":if("-"===a.charAt(b+3)){var e=a.indexOf("--\x3e",
b+4);if(e>b)return c.comment(a,b+4,e-b-4),e+3;d.error("Unclosed comment")}break;default:if("CDATA["==a.substr(b+3,6))return e=a.indexOf("]]\x3e",b+9),c.startCDATA(),c.characters(a,b+9,e-b-9),c.endCDATA(),e+3;a:{d=[];e=/'[^']+'|"[^"]+"|[^\s<>\/=]+=?|(\/?\s*>|<)/g;e.lastIndex=b;for(e.exec(a);b=e.exec(a);)if(d.push(b),b[1]){e=d;break a}e=void 0}var l=e.length;if(1<l&&/!doctype/i.test(e[0][0]))return a=e[1][0],b=3<l&&/^public$/i.test(e[2][0])&&e[3][0],d=4<l&&e[4][0],e=e[l-1],c.startDTD(a,b&&b.replace(/^(['"])(.*?)\1$/,
"$2"),d&&d.replace(/^(['"])(.*?)\1$/,"$2")),c.endDTD(),e.index+e[0].length}return-1}function l(a,b,c){var d=a.indexOf("?>",b);return d&&(a=a.substring(b,d).match(/^<\?(\S*)\s*([\s\S]*?)\s*$/))?(c.processingInstruction(a[1],a[2]),d+2):-1}function z(a){}function m(a,b){a.__proto__=b;return a}b=/[A-Z_a-z\xC0-\xD6\xD8-\xF6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFD]/;k=new RegExp("[\\-\\.0-9"+b.source.slice(1,-1)+"\u00b7\u0300-\u036f\\ux203F-\u2040]");
var C=new RegExp("^"+b.source+k.source+"*(?::"+b.source+k.source+"*)?$");h.prototype={parse:function(b,c,d){var e=this.domBuilder;e.startDocument();x(c,c={});a(b,c,d,e,this.errorHandler);e.endDocument()}};z.prototype={setTagName:function(a){if(!C.test(a))throw Error("invalid tagName:"+a);this.tagName=a},add:function(a,b,c){if(!C.test(a))throw Error("invalid attribute:"+a);this[this.length++]={qName:a,value:b,offset:c}},length:0,getLocalName:function(a){return this[a].localName},getOffset:function(a){return this[a].offset},
getQName:function(a){return this[a].qName},getURI:function(a){return this[a].uri},getValue:function(a){return this[a].value}};m({},m.prototype)instanceof m||(m=function(a,b){function c(){}c.prototype=b;c=new c;for(b in a)c[b]=a[b];return c});return h});
define("ace/mode/xml/dom",["require","exports","module"],function(b,k,p){function h(a,b){for(var c in a)b[c]=a[c]}function a(a,b){var c=a.prototype;if(Object.create){var d=Object.create(b.prototype);c.__proto__=d}c instanceof b||(d=function(){},d.prototype=b.prototype,d=new d,h(c,d),a.prototype=c=d);c.constructor!=a&&("function"!=typeof a&&console.error("unknow Class:"+a),c.constructor=a)}function c(a,b){if(b instanceof Error)var d=b;else d=this,Error.call(this,u[a]),this.message=u[a],Error.captureStackTrace&&
Error.captureStackTrace(this,c);d.code=a;b&&(this.message=this.message+": "+b);return d}function f(){}function e(a,b){this._node=a;this._refresh=b;d(this)}function d(a){var b=a._node._inc||a._node.ownerDocument._inc;if(a._inc!=b){var c=a._refresh(a._node);U(a,"length",c.length);h(c,a);a._inc=b}}function g(){}function x(a,b){for(var c=a.length;c--;)if(a[c]===b)return c}function E(a,b,c,d){d?b[x(b,d)]=c:b[b.length++]=c;a&&(c.ownerElement=a,b=a.ownerDocument)&&(d&&D(b,a,d),b&&b._inc++,"http://www.w3.org/2000/xmlns/"==
c.namespaceURI&&(a._nsMap[c.prefix?c.localName:""]=c.value))}function l(a,b,d){var e=x(b,d);if(0<=e){for(var n=b.length-1;e<n;)b[e]=b[++e];b.length=n;a&&(b=a.ownerDocument)&&(D(b,a,d),d.ownerElement=null)}else throw c(da,Error());}function z(a){this._features={};if(a)for(var b in a)this._features=a[b]}function m(){}function C(a){return"<"==a&&"&lt;"||">"==a&&"&gt;"||"&"==a&&"&amp;"||'"'==a&&"&quot;"||"&#"+a.charCodeAt()+";"}function t(a,b){if(b(a))return!0;if(a=a.firstChild){do if(t(a,b))return!0;
while(a=a.nextSibling)}}function I(){}function D(a,b,c,d){a&&a._inc++;"http://www.w3.org/2000/xmlns/"==c.namespaceURI&&delete b._nsMap[c.prefix?c.localName:""]}function R(a,b,c){if(a&&a._inc)if(a._inc++,a=b.childNodes,c)a[a.length++]=c;else{b=b.firstChild;for(c=0;b;)a[c++]=b,b=b.nextSibling;a.length=c}}function v(a,b){var c=b.previousSibling,d=b.nextSibling;c?c.nextSibling=d:a.firstChild=d;d?d.previousSibling=c:a.lastChild=c;R(a.ownerDocument,a);return b}function O(a,b,c){var d=b.parentNode;d&&d.removeChild(b);
if(b.nodeType===L){d=b.firstChild;if(null==d)return b;var e=b.lastChild}else d=e=b;var n=c?c.previousSibling:a.lastChild;d.previousSibling=n;e.nextSibling=c;n?n.nextSibling=d:a.firstChild=d;null==c?a.lastChild=e:c.previousSibling=e;do d.parentNode=a;while(d!==e&&(d=d.nextSibling));R(a.ownerDocument||a,a);b.nodeType==L&&(b.firstChild=b.lastChild=null);return b}function J(){this._nsMap={}}function q(){}function B(){}function P(){}function y(){}function n(){}function Q(){}function A(){}function r(){}
function s(){}function F(){}function K(){}function G(){}function T(a,b){switch(a.nodeType){case H:var c=a.attributes,d=c.length,e=a.firstChild,n=a.tagName,l="http://www.w3.org/1999/xhtml"===a.namespaceURI;b.push("<",n);for(var f=0;f<d;f++)T(c.item(f),b,l);if(e||l&&!/^(?:meta|link|img|br|hr|input|button)$/i.test(n)){b.push(">");if(l&&/^script$/i.test(n))e&&b.push(e.data);else for(;e;)T(e,b),e=e.nextSibling;b.push("</",n,">")}else b.push("/>");break;case X:case L:for(e=a.firstChild;e;)T(e,b),e=e.nextSibling;
break;case N:return b.push(" ",a.name,'="',a.value.replace(/[<&"]/g,C),'"');case S:return b.push(a.data.replace(/[<&]/g,C));case V:return b.push("<![CDATA[",a.data,"]]\x3e");case Y:return b.push("\x3c!--",a.data,"--\x3e");case Z:c=a.publicId;d=a.systemId;b.push("<!DOCTYPE ",a.name);c?(b.push(' PUBLIC "',c),d&&"."!=d&&b.push('" "',d),b.push('">')):d&&"."!=d?b.push(' SYSTEM "',d,'">'):((c=a.internalSubset)&&b.push(" [",c,"]"),b.push(">"));break;case $:return b.push("<?",a.target," ",a.data,"?>");case aa:return b.push("&",
a.nodeName,";");default:b.push("??",a.nodeName)}}function W(a,b,c){var d;switch(b.nodeType){case H:d=b.cloneNode(!1),d.ownerDocument=a;case L:break;case N:c=!0}d||(d=b.cloneNode(!1));d.ownerDocument=a;d.parentNode=null;if(c)for(b=b.firstChild;b;)d.appendChild(W(a,b,c)),b=b.nextSibling;return d}function M(a,b,c){var d=new b.constructor,e;for(e in b){var n=b[e];"object"!=typeof n&&n!=d[e]&&(d[e]=n)}b.childNodes&&(d.childNodes=new f);d.ownerDocument=a;switch(d.nodeType){case H:e=b.attributes;var l=d.attributes=
new g,n=e.length;l._ownerElement=d;for(l=0;l<n;l++)d.setAttributeNode(M(a,e.item(l),!0));break;case N:c=!0}if(c)for(b=b.firstChild;b;)d.appendChild(M(a,b,c)),b=b.nextSibling;return d}function U(a,b,c){a[b]=c}b={};var H=b.ELEMENT_NODE=1,N=b.ATTRIBUTE_NODE=2,S=b.TEXT_NODE=3,V=b.CDATA_SECTION_NODE=4,aa=b.ENTITY_REFERENCE_NODE=5;k=b.ENTITY_NODE=6;var $=b.PROCESSING_INSTRUCTION_NODE=7,Y=b.COMMENT_NODE=8,X=b.DOCUMENT_NODE=9,Z=b.DOCUMENT_TYPE_NODE=10,L=b.DOCUMENT_FRAGMENT_NODE=11;p=b.NOTATION_NODE=12;var w=
{},u={};w.INDEX_SIZE_ERR=(u[1]="Index size error",1);w.DOMSTRING_SIZE_ERR=(u[2]="DOMString size error",2);w.HIERARCHY_REQUEST_ERR=(u[3]="Hierarchy request error",3);w.WRONG_DOCUMENT_ERR=(u[4]="Wrong document",4);w.INVALID_CHARACTER_ERR=(u[5]="Invalid character",5);w.NO_DATA_ALLOWED_ERR=(u[6]="No data allowed",6);w.NO_MODIFICATION_ALLOWED_ERR=(u[7]="No modification allowed",7);var da=w.NOT_FOUND_ERR=(u[8]="Not found",8);w.NOT_SUPPORTED_ERR=(u[9]="Not supported",9);var ba=w.INUSE_ATTRIBUTE_ERR=(u[10]=
"Attribute in use",10);w.INVALID_STATE_ERR=(u[11]="Invalid state",11);w.SYNTAX_ERR=(u[12]="Syntax error",12);w.INVALID_MODIFICATION_ERR=(u[13]="Invalid modification",13);w.NAMESPACE_ERR=(u[14]="Invalid namespace",14);w.INVALID_ACCESS_ERR=(u[15]="Invalid access",15);c.prototype=Error.prototype;h(w,c);f.prototype={length:0,item:function(a){return this[a]||null}};e.prototype.item=function(a){d(this);return this[a]};a(e,f);g.prototype={length:0,item:f.prototype.item,getNamedItem:function(a){for(var b=
this.length;b--;){var c=this[b];if(c.nodeName==a)return c}},setNamedItem:function(a){var b=a.ownerElement;if(b&&b!=this._ownerElement)throw new c(ba);b=this.getNamedItem(a.nodeName);E(this._ownerElement,this,a,b);return b},setNamedItemNS:function(a){var b=a.ownerElement;if(b&&b!=this._ownerElement)throw new c(ba);b=this.getNamedItemNS(a.namespaceURI,a.localName);E(this._ownerElement,this,a,b);return b},removeNamedItem:function(a){a=this.getNamedItem(a);l(this._ownerElement,this,a);return a},removeNamedItemNS:function(a,
b){var c=this.getNamedItemNS(a,b);l(this._ownerElement,this,c);return c},getNamedItemNS:function(a,b){for(var c=this.length;c--;){var d=this[c];if(d.localName==b&&d.namespaceURI==a)return d}return null}};z.prototype={hasFeature:function(a,b){var c=this._features[a.toLowerCase()];return c&&(!b||b in c)?!0:!1},createDocument:function(a,b,c){var d=new I;d.implementation=this;d.childNodes=new f;(d.doctype=c)&&d.appendChild(c);b&&(a=d.createElementNS(a,b),d.appendChild(a));return d},createDocumentType:function(a,
b,c){var d=new Q;d.name=a;d.nodeName=a;d.publicId=b;d.systemId=c;return d}};m.prototype={firstChild:null,lastChild:null,previousSibling:null,nextSibling:null,attributes:null,parentNode:null,childNodes:null,ownerDocument:null,nodeValue:null,namespaceURI:null,prefix:null,localName:null,insertBefore:function(a,b){return O(this,a,b)},replaceChild:function(a,b){this.insertBefore(a,b);b&&this.removeChild(b)},removeChild:function(a){return v(this,a)},appendChild:function(a){return this.insertBefore(a,null)},
hasChildNodes:function(){return null!=this.firstChild},cloneNode:function(a){return M(this.ownerDocument||this,this,a)},normalize:function(){for(var a=this.firstChild;a;){var b=a.nextSibling;b&&b.nodeType==S&&a.nodeType==S?(this.removeChild(b),a.appendData(b.data)):(a.normalize(),a=b)}},isSupported:function(a,b){return this.ownerDocument.implementation.hasFeature(a,b)},hasAttributes:function(){return 0<this.attributes.length},lookupPrefix:function(a){for(var b=this;b;){var c=b._nsMap;if(c)for(var d in c)if(c[d]==
a)return d;b=2==b.nodeType?b.ownerDocument:b.parentNode}return null},lookupNamespaceURI:function(a){for(var b=this;b;){var c=b._nsMap;if(c&&a in c)return c[a];b=2==b.nodeType?b.ownerDocument:b.parentNode}return null},isDefaultNamespace:function(a){return null==this.lookupPrefix(a)}};h(b,m);h(b,m.prototype);I.prototype={nodeName:"#document",nodeType:X,doctype:null,documentElement:null,_inc:1,insertBefore:function(a,b){if(a.nodeType==L){for(var c=a.firstChild;c;){var d=c.nextSibling;this.insertBefore(c,
b);c=d}return a}null==this.documentElement&&1==a.nodeType&&(this.documentElement=a);return O(this,a,b),a.ownerDocument=this,a},removeChild:function(a){this.documentElement==a&&(this.documentElement=null);return v(this,a)},importNode:function(a,b){return W(this,a,b)},getElementById:function(a){var b=null;t(this.documentElement,function(c){if(1==c.nodeType&&c.getAttribute("id")==a)return b=c,!0});return b},createElement:function(a){var b=new J;b.ownerDocument=this;b.nodeName=a;b.tagName=a;b.childNodes=
new f;return(b.attributes=new g)._ownerElement=b},createDocumentFragment:function(){var a=new F;a.ownerDocument=this;a.childNodes=new f;return a},createTextNode:function(a){var b=new P;b.ownerDocument=this;b.appendData(a);return b},createComment:function(a){var b=new y;b.ownerDocument=this;b.appendData(a);return b},createCDATASection:function(a){var b=new n;b.ownerDocument=this;b.appendData(a);return b},createProcessingInstruction:function(a,b){var c=new K;c.ownerDocument=this;c.tagName=c.target=
a;c.nodeValue=c.data=b;return c},createAttribute:function(a){var b=new q;b.ownerDocument=this;b.name=a;b.nodeName=a;b.localName=a;b.specified=!0;return b},createEntityReference:function(a){var b=new s;b.ownerDocument=this;b.nodeName=a;return b},createElementNS:function(a,b){var c=new J,d=b.split(":"),e=c.attributes=new g;c.childNodes=new f;c.ownerDocument=this;c.nodeName=b;c.tagName=b;c.namespaceURI=a;2==d.length?(c.prefix=d[0],c.localName=d[1]):c.localName=b;return e._ownerElement=c},createAttributeNS:function(a,
b){var c=new q,d=b.split(":");c.ownerDocument=this;c.nodeName=b;c.name=b;c.namespaceURI=a;c.specified=!0;2==d.length?(c.prefix=d[0],c.localName=d[1]):c.localName=b;return c}};a(I,m);J.prototype={nodeType:H,hasAttribute:function(a){return null!=this.getAttributeNode(a)},getAttribute:function(a){return(a=this.getAttributeNode(a))&&a.value||""},getAttributeNode:function(a){return this.attributes.getNamedItem(a)},setAttribute:function(a,b){var c=this.ownerDocument.createAttribute(a);c.value=c.nodeValue=
""+b;this.setAttributeNode(c)},removeAttribute:function(a){(a=this.getAttributeNode(a))&&this.removeAttributeNode(a)},appendChild:function(a){if(a.nodeType===L)return this.insertBefore(a,null);var b=a.parentNode;if(b){var c=this.lastChild;b.removeChild(a)}c=this.lastChild;a.parentNode=this;a.previousSibling=c;a.nextSibling=null;c?c.nextSibling=a:this.firstChild=a;this.lastChild=a;R(this.ownerDocument,this,a);return a},setAttributeNode:function(a){return this.attributes.setNamedItem(a)},setAttributeNodeNS:function(a){return this.attributes.setNamedItemNS(a)},
removeAttributeNode:function(a){return this.attributes.removeNamedItem(a.nodeName)},removeAttributeNS:function(a,b){var c=this.getAttributeNodeNS(a,b);c&&this.removeAttributeNode(c)},hasAttributeNS:function(a,b){return null!=this.getAttributeNodeNS(a,b)},getAttributeNS:function(a,b){var c=this.getAttributeNodeNS(a,b);return c&&c.value||""},setAttributeNS:function(a,b,c){a=this.ownerDocument.createAttributeNS(a,b);a.value=a.nodeValue=""+c;this.setAttributeNode(a)},getAttributeNodeNS:function(a,b){return this.attributes.getNamedItemNS(a,
b)},getElementsByTagName:function(a){return new e(this,function(b){var c=[];t(b,function(d){d===b||d.nodeType!=H||"*"!==a&&d.tagName!=a||c.push(d)});return c})},getElementsByTagNameNS:function(a,b){return new e(this,function(c){var d=[];t(c,function(e){e===c||e.nodeType!==H||"*"!==a&&e.namespaceURI!==a||"*"!==b&&e.localName!=b||d.push(e)});return d})}};I.prototype.getElementsByTagName=J.prototype.getElementsByTagName;I.prototype.getElementsByTagNameNS=J.prototype.getElementsByTagNameNS;a(J,m);q.prototype.nodeType=
N;a(q,m);B.prototype={data:"",substringData:function(a,b){return this.data.substring(a,a+b)},appendData:function(a){this.nodeValue=this.data=a=this.data+a;this.length=a.length},insertData:function(a,b){this.replaceData(a,0,b)},appendChild:function(a){throw Error(u[3]);},deleteData:function(a,b){this.replaceData(a,b,"")},replaceData:function(a,b,c){var d=this.data.substring(0,a);a=this.data.substring(a+b);this.nodeValue=this.data=c=d+c+a;this.length=c.length}};a(B,m);P.prototype={nodeName:"#text",
nodeType:S,splitText:function(a){var b=this.data,c=b.substring(a);this.data=this.nodeValue=b=b.substring(0,a);this.length=b.length;a=this.ownerDocument.createTextNode(c);this.parentNode&&this.parentNode.insertBefore(a,this.nextSibling);return a}};a(P,B);y.prototype={nodeName:"#comment",nodeType:Y};a(y,B);n.prototype={nodeName:"#cdata-section",nodeType:V};a(n,B);Q.prototype.nodeType=Z;a(Q,m);A.prototype.nodeType=p;a(A,m);r.prototype.nodeType=k;a(r,m);s.prototype.nodeType=aa;a(s,m);F.prototype.nodeName=
"#document-fragment";F.prototype.nodeType=L;a(F,m);K.prototype.nodeType=$;a(K,m);G.prototype.serializeToString=function(a){var b=[];T(a,b);return b.join("")};m.prototype.toString=function(){return G.prototype.serializeToString(this)};try{if(Object.defineProperty){var ca=function(a){switch(a.nodeType){case 1:case 11:var b=[];for(a=a.firstChild;a;)7!==a.nodeType&&8!==a.nodeType&&b.push(ca(a)),a=a.nextSibling;return b.join("");default:return a.nodeValue}};Object.defineProperty(e.prototype,"length",{get:function(){d(this);
return this.$$length}});Object.defineProperty(m.prototype,"textContent",{get:function(){return ca(this)},set:function(a){switch(this.nodeType){case 1:case 11:for(;this.firstChild;)this.removeChild(this.firstChild);(a||String(a))&&this.appendChild(this.ownerDocument.createTextNode(a));break;default:this.data=a,this.value=value,this.nodeValue=a}}});U=function(a,b,c){a["$$"+b]=c}}}catch(ea){}return z});
define("ace/mode/xml/dom-parser",["require","exports","module","ace/mode/xml/sax","ace/mode/xml/dom"],function(b,k,p){function h(a){this.options=a||{locator:{}}}function a(a,b,d){function f(b){var c=a[b];if(!c)if(k)c=2==a.length?function(c){a(b,c)}:a;else for(var h=arguments.length;--h&&!(c=a[arguments[h]]););g[b]=c&&function(a){c(a+e(d),a,d)}||function(){}}if(!a){if(b instanceof c)return b;a=b}var g={},k=a instanceof Function;d=d||{};f("warning","warn");f("error","warn","warning");f("fatalError",
"warn","warning","error");return g}function c(){this.cdata=!1}function f(a,b){b.lineNumber=a.lineNumber;b.columnNumber=a.columnNumber}function e(a){if(a)return"\n@"+(a.systemId||"")+"#[line:"+a.lineNumber+",col:"+a.columnNumber+"]"}function d(a,b,c){return"string"==typeof a?a.substr(b,c):a.length>=b+c||b?new java.lang.String(a,b,c)+"":a}function g(a,b){a.currentElement?a.currentElement.appendChild(b):a.document.appendChild(b)}var x=b("./sax"),E=b("./dom");h.prototype.parseFromString=function(b,d){var e=
this.options,f=new x,g=e.domBuilder||new c,k=e.errorHandler,h=e.locator,p=e.xmlns||{},v={lt:"<",gt:">",amp:"&",quot:'"',apos:"'"};h&&g.setDocumentLocator(h);f.errorHandler=a(k,g,h);f.domBuilder=e.domBuilder||g;/\/x?html?$/.test(d)&&(v.nbsp="\u00a0",v.copy="\u00a9",p[""]="http://www.w3.org/1999/xhtml");b?f.parse(b,p,v):f.errorHandler.error("invalid document source");return g.document};c.prototype={startDocument:function(){this.document=(new E).createDocument(null,null,null);this.locator&&(this.document.documentURI=
this.locator.systemId)},startElement:function(a,b,c,d){var e=this.document;b=e.createElementNS(a,c||b);var k=d.length;g(this,b);this.currentElement=b;this.locator&&f(this.locator,b);for(var h=0;h<k;h++){a=d.getURI(h);var p=d.getValue(h);c=d.getQName(h);a=e.createAttributeNS(a,c);a.getOffset&&f(a.getOffset(1),a);a.value=a.nodeValue=p;b.setAttributeNode(a)}},endElement:function(a,b,c){this.currentElement=this.currentElement.parentNode},startPrefixMapping:function(a,b){},endPrefixMapping:function(a){},
processingInstruction:function(a,b){var c=this.document.createProcessingInstruction(a,b);this.locator&&f(this.locator,c);g(this,c)},ignorableWhitespace:function(a,b,c){},characters:function(a,b,c){a=d.apply(this,arguments);if(this.currentElement&&a){var e=this.cdata?this.document.createCDATASection(a):this.document.createTextNode(a);this.currentElement.appendChild(e);this.locator&&f(this.locator,e)}},skippedEntity:function(a){},endDocument:function(){this.document.normalize()},setDocumentLocator:function(a){if(this.locator=
a)a.lineNumber=0},comment:function(a,b,c){a=d.apply(this,arguments);var e=this.document.createComment(a);this.locator&&f(this.locator,e);g(this,e)},startCDATA:function(){this.cdata=!0},endCDATA:function(){this.cdata=!1},startDTD:function(a,b,c){var d=this.document.implementation;d&&d.createDocumentType&&(a=d.createDocumentType(a,b,c),this.locator&&f(this.locator,a),g(this,a))},warning:function(a){console.warn(a,e(this.locator))},error:function(a){console.error(a,e(this.locator))},fatalError:function(a){console.error(a,
e(this.locator));throw a;}};"endDTD,startEntity,endEntity,attributeDecl,elementDecl,externalEntityDecl,internalEntityDecl,resolveEntity,getExternalSubset,notationDecl,unparsedEntityDecl".replace(/\w+/g,function(a){c.prototype[a]=function(){return null}});return{DOMParser:h}});
define("ace/mode/xml_worker","require exports module ace/lib/oop ace/lib/lang ace/worker/mirror ace/mode/xml/dom-parser".split(" "),function(b,k,p){p=b("../lib/oop");b("../lib/lang");var h=b("../worker/mirror").Mirror,a=b("./xml/dom-parser").DOMParser;b=k.Worker=function(a){h.call(this,a);this.setTimeout(400);this.context=null};p.inherits(b,h);(function(){this.setOptions=function(a){this.context=a.context};this.onUpdate=function(){var b=this.doc.getValue();if(b){var f=new a,e=[];f.options.errorHandler=
{fatalError:function(a,b,c){e.push({row:c.lineNumber,column:c.columnNumber,text:b,type:"error"})},error:function(a,b,c){e.push({row:c.lineNumber,column:c.columnNumber,text:b,type:"error"})},warning:function(a,b,c){e.push({row:c.lineNumber,column:c.columnNumber,text:b,type:"warning"})}};f.parseFromString(b);this.sender.emit("error",e)}}}).call(b.prototype)});
define("ace/lib/es5-shim",["require","exports","module"],function(b,k,p){function h(){}function a(a){try{return Object.defineProperty(a,"sentinel",{}),"sentinel"in a}catch(b){}}function c(a){a=+a;a!==a?a=0:0!==a&&a!==1/0&&a!==-(1/0)&&(a=(0<a||-1)*Math.floor(Math.abs(a)));return a}Function.prototype.bind||(Function.prototype.bind=function(a){var b=this;if("function"!=typeof b)throw new TypeError("Function.prototype.bind called on incompatible "+b);var c=e.call(arguments,1),d=function(){if(this instanceof
d){var f=b.apply(this,c.concat(e.call(arguments)));return Object(f)===f?f:this}return b.apply(a,c.concat(e.call(arguments)))};b.prototype&&(h.prototype=b.prototype,d.prototype=new h,h.prototype=null);return d});b=Function.prototype.call;var f=Object.prototype,e=Array.prototype.slice,d=b.bind(f.toString),g=b.bind(f.hasOwnProperty),x,E,l,z,m;if(m=g(f,"__defineGetter__"))x=b.bind(f.__defineGetter__),E=b.bind(f.__defineSetter__),l=b.bind(f.__lookupGetter__),z=b.bind(f.__lookupSetter__);if(2!=[1,2].splice(0).length)if(function(){function a(b){b=
Array(b+2);b[0]=b[1]=0;return b}var b=[],c;b.splice.apply(b,a(20));b.splice.apply(b,a(26));c=b.length;b.splice(5,0,"XXX");c+1==b.length;if(c+1==b.length)return!0}()){var C=Array.prototype.splice;Array.prototype.splice=function(a,b){return arguments.length?C.apply(this,[void 0===a?0:a,void 0===b?this.length-a:b].concat(e.call(arguments,2))):[]}}else Array.prototype.splice=function(a,b){var c=this.length;0<a?a>c&&(a=c):void 0==a?a=0:0>a&&(a=Math.max(c+a,0));a+b<c||(b=c-a);var d=this.slice(a,a+b),f=
e.call(arguments,2),g=f.length;if(a===c)g&&this.push.apply(this,f);else{var h=Math.min(b,c-a),k=a+h,l=k+g-h,m=c-k,c=c-h;if(l<k)for(h=0;h<m;++h)this[l+h]=this[k+h];else if(l>k)for(h=m;h--;)this[l+h]=this[k+h];if(g&&a===c)this.length=c,this.push.apply(this,f);else for(this.length=c+g,h=0;h<g;++h)this[a+h]=f[h]}return d};Array.isArray||(Array.isArray=function(a){return"[object Array]"==d(a)});b=Object("a");var t="a"!=b[0]||!(0 in b);Array.prototype.forEach||(Array.prototype.forEach=function(a,b){var c=
y(this),e=t&&"[object String]"==d(this)?this.split(""):c,f=-1,g=e.length>>>0;if("[object Function]"!=d(a))throw new TypeError;for(;++f<g;)f in e&&a.call(b,e[f],f,c)});Array.prototype.map||(Array.prototype.map=function(a,b){var c=y(this),e=t&&"[object String]"==d(this)?this.split(""):c,f=e.length>>>0,g=Array(f);if("[object Function]"!=d(a))throw new TypeError(a+" is not a function");for(var h=0;h<f;h++)h in e&&(g[h]=a.call(b,e[h],h,c));return g});Array.prototype.filter||(Array.prototype.filter=function(a,
b){var c=y(this),e=t&&"[object String]"==d(this)?this.split(""):c,f=e.length>>>0,g=[],h;if("[object Function]"!=d(a))throw new TypeError(a+" is not a function");for(var k=0;k<f;k++)k in e&&(h=e[k],a.call(b,h,k,c)&&g.push(h));return g});Array.prototype.every||(Array.prototype.every=function(a,b){var c=y(this),e=t&&"[object String]"==d(this)?this.split(""):c,f=e.length>>>0;if("[object Function]"!=d(a))throw new TypeError(a+" is not a function");for(var g=0;g<f;g++)if(g in e&&!a.call(b,e[g],g,c))return!1;
return!0});Array.prototype.some||(Array.prototype.some=function(a,b){var c=y(this),e=t&&"[object String]"==d(this)?this.split(""):c,f=e.length>>>0;if("[object Function]"!=d(a))throw new TypeError(a+" is not a function");for(var g=0;g<f;g++)if(g in e&&a.call(b,e[g],g,c))return!0;return!1});Array.prototype.reduce||(Array.prototype.reduce=function(a){var b=y(this),c=t&&"[object String]"==d(this)?this.split(""):b,e=c.length>>>0;if("[object Function]"!=d(a))throw new TypeError(a+" is not a function");
if(!e&&1==arguments.length)throw new TypeError("reduce of empty array with no initial value");var f=0,g;if(2<=arguments.length)g=arguments[1];else{do{if(f in c){g=c[f++];break}if(++f>=e)throw new TypeError("reduce of empty array with no initial value");}while(1)}for(;f<e;f++)f in c&&(g=a.call(void 0,g,c[f],f,b));return g});Array.prototype.reduceRight||(Array.prototype.reduceRight=function(a){var b=y(this),c=t&&"[object String]"==d(this)?this.split(""):b,e=c.length>>>0;if("[object Function]"!=d(a))throw new TypeError(a+
" is not a function");if(!e&&1==arguments.length)throw new TypeError("reduceRight of empty array with no initial value");var f,e=e-1;if(2<=arguments.length)f=arguments[1];else{do{if(e in c){f=c[e--];break}if(0>--e)throw new TypeError("reduceRight of empty array with no initial value");}while(1)}do e in this&&(f=a.call(void 0,f,c[e],e,b));while(e--);return f});Array.prototype.indexOf&&-1==[0,1].indexOf(1,2)||(Array.prototype.indexOf=function(a){var b=t&&"[object String]"==d(this)?this.split(""):y(this),
e=b.length>>>0;if(!e)return-1;var f=0;1<arguments.length&&(f=c(arguments[1]));for(f=0<=f?f:Math.max(0,e+f);f<e;f++)if(f in b&&b[f]===a)return f;return-1});Array.prototype.lastIndexOf&&-1==[0,1].lastIndexOf(0,-3)||(Array.prototype.lastIndexOf=function(a){var b=t&&"[object String]"==d(this)?this.split(""):y(this),e=b.length>>>0;if(!e)return-1;var f=e-1;1<arguments.length&&(f=Math.min(f,c(arguments[1])));for(f=0<=f?f:e-Math.abs(f);0<=f;f--)if(f in b&&a===b[f])return f;return-1});Object.getPrototypeOf||
(Object.getPrototypeOf=function(a){return a.__proto__||(a.constructor?a.constructor.prototype:f)});Object.getOwnPropertyDescriptor||(Object.getOwnPropertyDescriptor=function(a,b){if("object"!=typeof a&&"function"!=typeof a||null===a)throw new TypeError("Object.getOwnPropertyDescriptor called on a non-object: "+a);if(g(a,b)){var c,d,e;c={enumerable:!0,configurable:!0};if(m){var h=a.__proto__;a.__proto__=f;d=l(a,b);e=z(a,b);a.__proto__=h;if(d||e)return d&&(c.get=d),e&&(c.set=e),c}c.value=a[b];return c}});
Object.getOwnPropertyNames||(Object.getOwnPropertyNames=function(a){return Object.keys(a)});if(!Object.create){var I;I=null===Object.prototype.__proto__?function(){return{__proto__:null}}:function(){var a={},b;for(b in a)a[b]=null;a.constructor=a.hasOwnProperty=a.propertyIsEnumerable=a.isPrototypeOf=a.toLocaleString=a.toString=a.valueOf=a.__proto__=null;return a};Object.create=function(a,b){var c;if(null===a)c=I();else{if("object"!=typeof a)throw new TypeError("typeof prototype["+typeof a+"] != 'object'");
c=function(){};c.prototype=a;c=new c;c.__proto__=a}void 0!==b&&Object.defineProperties(c,b);return c}}if(Object.defineProperty&&(b=a({}),k="undefined"==typeof document||a(document.createElement("div")),!b||!k))var D=Object.defineProperty;if(!Object.defineProperty||D)Object.defineProperty=function(a,b,c){if("object"!=typeof a&&"function"!=typeof a||null===a)throw new TypeError("Object.defineProperty called on non-object: "+a);if("object"!=typeof c&&"function"!=typeof c||null===c)throw new TypeError("Property description must be an object: "+
c);if(D)try{return D.call(Object,a,b,c)}catch(d){}if(g(c,"value"))if(m&&(l(a,b)||z(a,b))){var e=a.__proto__;a.__proto__=f;delete a[b];a[b]=c.value;a.__proto__=e}else a[b]=c.value;else{if(!m)throw new TypeError("getters & setters can not be defined on this javascript engine");g(c,"get")&&x(a,b,c.get);g(c,"set")&&E(a,b,c.set)}return a};Object.defineProperties||(Object.defineProperties=function(a,b){for(var c in b)g(b,c)&&Object.defineProperty(a,c,b[c]);return a});Object.seal||(Object.seal=function(a){return a});
Object.freeze||(Object.freeze=function(a){return a});try{Object.freeze(function(){})}catch(R){Object.freeze=function(a){return function(b){return"function"==typeof b?b:a(b)}}(Object.freeze)}Object.preventExtensions||(Object.preventExtensions=function(a){return a});Object.isSealed||(Object.isSealed=function(a){return!1});Object.isFrozen||(Object.isFrozen=function(a){return!1});Object.isExtensible||(Object.isExtensible=function(a){if(Object(a)===a)throw new TypeError;for(var b="";g(a,b);)b+="?";a[b]=
!0;var c=g(a,b);delete a[b];return c});if(!Object.keys){var v=!0,O="toString toLocaleString valueOf hasOwnProperty isPrototypeOf propertyIsEnumerable constructor".split(" "),J=O.length,q;for(q in{toString:null})v=!1;Object.keys=function(a){if("object"!=typeof a&&"function"!=typeof a||null===a)throw new TypeError("Object.keys called on a non-object");var b=[],c;for(c in a)g(a,c)&&b.push(c);if(v)for(c=0;c<J;c++){var d=O[c];g(a,d)&&b.push(d)}return b}}Date.now||(Date.now=function(){return(new Date).getTime()});
q="\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000\u2028\u2029\ufeff";if(!String.prototype.trim||q.trim()){q="["+q+"]";var B=new RegExp("^"+q+q+"*"),P=new RegExp(q+q+"*$");String.prototype.trim=function(){return String(this).replace(B,"").replace(P,"")}}var y=function(a){if(null==a)throw new TypeError("can't convert "+a+" to object");return Object(a)}});
