"no use strict";
(function(d){function h(a,c){for(var e=a,f="";e;){var b=c[e];if("string"==typeof b)return b+f;if(b)return b.location.replace(/\/*$/,"/")+(f||b.main||b.name);if(!1===b)return"";b=e.lastIndexOf("/");if(-1===b)break;f=e.substr(b)+f;e=e.slice(0,b)}return a}if("undefined"==typeof d.window||!d.document)if(!d.require||!d.define){d.console=function(){var a=Array.prototype.slice.call(arguments,0);postMessage({type:"log",data:a})};d.console.error=d.console.warn=d.console.log=d.console.trace=d.console;d.window=
d;d.ace=d;d.onerror=function(a,c,e,f,b){postMessage({type:"error",data:{message:a,data:b.data,file:c,line:e,col:f,stack:b.stack}})};d.normalizeModule=function(a,c){if(-1!==c.indexOf("!")){var e=c.split("!");return d.normalizeModule(a,e[0])+"!"+d.normalizeModule(a,e[1])}if("."==c.charAt(0))for(e=a.split("/").slice(0,-1).join("/"),c=(e?e+"/":"")+c;-1!==c.indexOf(".")&&f!=c;){var f=c;c=c.replace(/^\.\//,"").replace(/\/\.\//,"/").replace(/[^\/]+\/\.\.\//,"")}return c};d.require=function(a,c){c||(c=a,
a=null);if(!c.charAt)throw Error("worker.js require() accepts only (parentId, id) as arguments");c=d.normalizeModule(a,c);var e=d.require.modules[c];if(e)return e.initialized||(e.initialized=!0,e.exports=e.factory().exports),e.exports;if(!d.require.tlns)return console.log("unable to load "+c);e=h(c,d.require.tlns);".js"!=e.slice(-3)&&(e+=".js");d.require.id=c;d.require.modules[c]={};importScripts(e);return d.require(a,c)};d.require.modules={};d.require.tlns={};d.define=function(a,c,e){2==arguments.length?
(e=c,"string"!=typeof a&&(c=a,a=d.require.id)):1==arguments.length&&(e=a,c=[],a=d.require.id);if("function"!=typeof e)d.require.modules[a]={exports:e,initialized:!0};else{c.length||(c=["require","exports","module"]);var f=function(b){return d.require(a,b)};d.require.modules[a]={exports:{},factory:function(){var b=this,a=e.apply(this,c.map(function(a){switch(a){case "require":return f;case "exports":return b.exports;case "module":return b;default:return f(a)}}));a&&(b.exports=a);return b}}}};d.define.amd=
{};require.tlns={};d.initBaseUrls=function(a){for(var c in a)require.tlns[c]=a[c]};d.initSender=function(){var a=d.require("ace/lib/event_emitter").EventEmitter,c=d.require("ace/lib/oop"),e=function(){};(function(){c.implement(this,a);this.callback=function(a,b){postMessage({type:"call",id:b,data:a})};this.emit=function(a,b){postMessage({type:"event",name:a,data:b})}}).call(e.prototype);return new e};var l=d.main=null,g=d.sender=null;d.onmessage=function(a){a=a.data;if(a.event&&g)g._signal(a.event,
a.data);else if(a.command)if(l[a.command])l[a.command].apply(l,a.args);else if(d[a.command])d[a.command].apply(d,a.args);else throw Error("Unknown command:"+a.command);else a.init&&(d.initBaseUrls(a.tlns),require("ace/lib/es5-shim"),g=d.sender=d.initSender(),a=require(a.module)[a.classname],l=d.main=new a(g))}}})(this);
define("ace/lib/oop",["require","exports","module"],function(d,h,l){h.inherits=function(d,a){d.super_=a;d.prototype=Object.create(a.prototype,{constructor:{value:d,enumerable:!1,writable:!0,configurable:!0}})};h.mixin=function(d,a){for(var c in a)d[c]=a[c];return d};h.implement=function(d,a){h.mixin(d,a)}});
define("ace/range",["require","exports","module"],function(d,h,l){var g=function(a,c,e,f){this.start={row:a,column:c};this.end={row:e,column:f}};(function(){this.isEqual=function(a){return this.start.row===a.start.row&&this.end.row===a.end.row&&this.start.column===a.start.column&&this.end.column===a.end.column};this.toString=function(){return"Range: ["+this.start.row+"/"+this.start.column+"] -> ["+this.end.row+"/"+this.end.column+"]"};this.contains=function(a,c){return 0==this.compare(a,c)};this.compareRange=
function(a){var c;c=a.end;a=a.start;c=this.compare(c.row,c.column);if(1==c)return c=this.compare(a.row,a.column),1==c?2:0==c?1:0;if(-1==c)return-2;c=this.compare(a.row,a.column);return-1==c?-1:1==c?42:0};this.comparePoint=function(a){return this.compare(a.row,a.column)};this.containsRange=function(a){return 0==this.comparePoint(a.start)&&0==this.comparePoint(a.end)};this.intersects=function(a){a=this.compareRange(a);return-1==a||0==a||1==a};this.isEnd=function(a,c){return this.end.row==a&&this.end.column==
c};this.isStart=function(a,c){return this.start.row==a&&this.start.column==c};this.setStart=function(a,c){"object"==typeof a?(this.start.column=a.column,this.start.row=a.row):(this.start.row=a,this.start.column=c)};this.setEnd=function(a,c){"object"==typeof a?(this.end.column=a.column,this.end.row=a.row):(this.end.row=a,this.end.column=c)};this.inside=function(a,c){return 0!=this.compare(a,c)||this.isEnd(a,c)||this.isStart(a,c)?!1:!0};this.insideStart=function(a,c){return 0!=this.compare(a,c)||this.isEnd(a,
c)?!1:!0};this.insideEnd=function(a,c){return 0!=this.compare(a,c)||this.isStart(a,c)?!1:!0};this.compare=function(a,c){return this.isMultiLine()||a!==this.start.row?a<this.start.row?-1:a>this.end.row?1:this.start.row===a?c>=this.start.column?0:-1:this.end.row===a?c<=this.end.column?0:1:0:c<this.start.column?-1:c>this.end.column?1:0};this.compareStart=function(a,c){return this.start.row==a&&this.start.column==c?-1:this.compare(a,c)};this.compareEnd=function(a,c){return this.end.row==a&&this.end.column==
c?1:this.compare(a,c)};this.compareInside=function(a,c){return this.end.row==a&&this.end.column==c?1:this.start.row==a&&this.start.column==c?-1:this.compare(a,c)};this.clipRows=function(a,c){if(this.end.row>c)var e={row:c+1,column:0};else this.end.row<a&&(e={row:a,column:0});if(this.start.row>c)var f={row:c+1,column:0};else this.start.row<a&&(f={row:a,column:0});return g.fromPoints(f||this.start,e||this.end)};this.extend=function(a,c){var e=this.compare(a,c);if(0==e)return this;if(-1==e)var f={row:a,
column:c};else var b={row:a,column:c};return g.fromPoints(f||this.start,b||this.end)};this.isEmpty=function(){return this.start.row===this.end.row&&this.start.column===this.end.column};this.isMultiLine=function(){return this.start.row!==this.end.row};this.clone=function(){return g.fromPoints(this.start,this.end)};this.collapseRows=function(){return 0==this.end.column?new g(this.start.row,0,Math.max(this.start.row,this.end.row-1),0):new g(this.start.row,0,this.end.row,0)};this.toScreenRange=function(a){var c=
a.documentToScreenPosition(this.start);a=a.documentToScreenPosition(this.end);return new g(c.row,c.column,a.row,a.column)};this.moveBy=function(a,c){this.start.row+=a;this.start.column+=c;this.end.row+=a;this.end.column+=c}}).call(g.prototype);g.fromPoints=function(a,c){return new g(a.row,a.column,c.row,c.column)};g.comparePoints=function(a,c){return a.row-c.row||a.column-c.column};g.comparePoints=function(a,c){return a.row-c.row||a.column-c.column};h.Range=g});
define("ace/apply_delta",["require","exports","module"],function(d,h,l){h.applyDelta=function(d,a,c){c=a.start.row;var e=a.start.column,f=d[c]||"";switch(a.action){case "insert":if(1===a.lines.length)d[c]=f.substring(0,e)+a.lines[0]+f.substring(e);else{var b=[c,1].concat(a.lines);d.splice.apply(d,b);d[c]=f.substring(0,e)+d[c];d[c+a.lines.length-1]+=f.substring(e)}break;case "remove":b=a.end.column,a=a.end.row,c===a?d[c]=f.substring(0,e)+f.substring(b):d.splice(c,a-c+1,f.substring(0,e)+d[a].substring(b))}}});
define("ace/lib/event_emitter",["require","exports","module"],function(d,h,l){d={};var g=function(){this.propagationStopped=!0},a=function(){this.defaultPrevented=!0};d._emit=d._dispatchEvent=function(c,e){this._eventRegistry||(this._eventRegistry={});this._defaultHandlers||(this._defaultHandlers={});var f=this._eventRegistry[c]||[],b=this._defaultHandlers[c];if(f.length||b){"object"==typeof e&&e||(e={});e.type||(e.type=c);e.stopPropagation||(e.stopPropagation=g);e.preventDefault||(e.preventDefault=
a);for(var f=f.slice(),k=0;k<f.length&&(f[k](e,this),!e.propagationStopped);k++);if(b&&!e.defaultPrevented)return b(e,this)}};d._signal=function(a,e){var f=(this._eventRegistry||{})[a];if(f)for(var f=f.slice(),b=0;b<f.length;b++)f[b](e,this)};d.once=function(a,e){var f=this;e&&this.addEventListener(a,function k(){f.removeEventListener(a,k);e.apply(null,arguments)})};d.setDefaultHandler=function(a,e){var f=this._defaultHandlers;f||(f=this._defaultHandlers={_disabled_:{}});if(f[a]){var b=f[a],k=f._disabled_[a];
k||(f._disabled_[a]=k=[]);k.push(b);b=k.indexOf(e);-1!=b&&k.splice(b,1)}f[a]=e};d.removeDefaultHandler=function(a,e){var f=this._defaultHandlers;if(f){var b=f._disabled_[a];f[a]==e?b&&this.setDefaultHandler(a,b.pop()):b&&(f=b.indexOf(e),-1!=f&&b.splice(f,1))}};d.on=d.addEventListener=function(a,e,f){this._eventRegistry=this._eventRegistry||{};var b=this._eventRegistry[a];b||(b=this._eventRegistry[a]=[]);if(-1==b.indexOf(e))b[f?"unshift":"push"](e);return e};d.off=d.removeListener=d.removeEventListener=
function(a,e){this._eventRegistry=this._eventRegistry||{};var f=this._eventRegistry[a];if(f){var b=f.indexOf(e);-1!==b&&f.splice(b,1)}};d.removeAllListeners=function(a){this._eventRegistry&&(this._eventRegistry[a]=[])};h.EventEmitter=d});
define("ace/anchor",["require","exports","module","ace/lib/oop","ace/lib/event_emitter"],function(d,h,l){var g=d("./lib/oop"),a=d("./lib/event_emitter").EventEmitter;d=h.Anchor=function(a,e,f){this.$onChange=this.onChange.bind(this);this.attach(a);"undefined"==typeof f?this.setPosition(e.row,e.column):this.setPosition(e,f)};(function(){function c(a,c,b){b=b?a.column<=c.column:a.column<c.column;return a.row<c.row||a.row==c.row&&b}g.implement(this,a);this.getPosition=function(){return this.$clipPositionToDocument(this.row,
this.column)};this.getDocument=function(){return this.document};this.$insertRight=!1;this.onChange=function(a){var f,b;if(!(a.start.row==a.end.row&&a.start.row!=this.row||a.start.row>this.row)){b={row:this.row,column:this.column};f=this.$insertRight;var k="insert"==a.action,d=(k?1:-1)*(a.end.row-a.start.row),h=(k?1:-1)*(a.end.column-a.start.column),g=a.start;a=k?g:a.end;c(b,g,f)?(f=b.row,b=b.column):c(a,b,!f)?(f=b.row+d,b=b.column+(b.row==a.row?h:0)):(f=g.row,b=g.column);this.setPosition(f,b,!0)}};
this.setPosition=function(a,c,b){a=b?{row:a,column:c}:this.$clipPositionToDocument(a,c);if(this.row!=a.row||this.column!=a.column)c={row:this.row,column:this.column},this.row=a.row,this.column=a.column,this._signal("change",{old:c,value:a})};this.detach=function(){this.document.removeEventListener("change",this.$onChange)};this.attach=function(a){this.document=a||this.document;this.document.on("change",this.$onChange)};this.$clipPositionToDocument=function(a,c){var b={};a>=this.document.getLength()?
(b.row=Math.max(0,this.document.getLength()-1),b.column=this.document.getLine(b.row).length):0>a?(b.row=0,b.column=0):(b.row=a,b.column=Math.min(this.document.getLine(b.row).length,Math.max(0,c)));0>c&&(b.column=0);return b}}).call(d.prototype)});
define("ace/document","require exports module ace/lib/oop ace/apply_delta ace/lib/event_emitter ace/range ace/anchor".split(" "),function(d,h,l){var g=d("./lib/oop"),a=d("./apply_delta").applyDelta,c=d("./lib/event_emitter").EventEmitter,e=d("./range").Range,f=d("./anchor").Anchor;d=function(b){this.$lines=[""];0===b.length?this.$lines=[""]:Array.isArray(b)?this.insertMergedLines({row:0,column:0},b):this.insert({row:0,column:0},b)};(function(){g.implement(this,c);this.setValue=function(b){var a=this.getLength()-
1;this.remove(new e(0,0,a,this.getLine(a).length));this.insert({row:0,column:0},b)};this.getValue=function(){return this.getAllLines().join(this.getNewLineCharacter())};this.createAnchor=function(b,a){return new f(this,b,a)};0==="aaa".split(/a/).length?this.$split=function(b){return b.replace(/\r\n|\r/g,"\n").split("\n")}:this.$split=function(b){return b.split(/\r\n|\r|\n/)};this.$detectNewLine=function(b){this.$autoNewLine=(b=b.match(/^.*?(\r\n|\r|\n)/m))?b[1]:"\n";this._signal("changeNewLineMode")};
this.getNewLineCharacter=function(){switch(this.$newLineMode){case "windows":return"\r\n";case "unix":return"\n";default:return this.$autoNewLine||"\n"}};this.$autoNewLine="";this.$newLineMode="auto";this.setNewLineMode=function(b){this.$newLineMode!==b&&(this.$newLineMode=b,this._signal("changeNewLineMode"))};this.getNewLineMode=function(){return this.$newLineMode};this.isNewLine=function(b){return"\r\n"==b||"\r"==b||"\n"==b};this.getLine=function(b){return this.$lines[b]||""};this.getLines=function(b,
a){return this.$lines.slice(b,a+1)};this.getAllLines=function(){return this.getLines(0,this.getLength())};this.getLength=function(){return this.$lines.length};this.getTextRange=function(b){return this.getLinesForRange(b).join(this.getNewLineCharacter())};this.getLinesForRange=function(b){var a;if(b.start.row===b.end.row)a=[this.getLine(b.start.row).substring(b.start.column,b.end.column)];else{a=this.getLines(b.start.row,b.end.row);a[0]=(a[0]||"").substring(b.start.column);var c=a.length-1;b.end.row-
b.start.row==c&&(a[c]=a[c].substring(0,b.end.column))}return a};this.insertLines=function(b,a){console.warn("Use of document.insertLines is deprecated. Use the insertFullLines method instead.");return this.insertFullLines(b,a)};this.removeLines=function(b,a){console.warn("Use of document.removeLines is deprecated. Use the removeFullLines method instead.");return this.removeFullLines(b,a)};this.insertNewLine=function(b){console.warn("Use of document.insertNewLine is deprecated. Use insertMergedLines(position, ['', '']) instead.");
return this.insertMergedLines(b,["",""])};this.insert=function(b,a){1>=this.getLength()&&this.$detectNewLine(a);return this.insertMergedLines(b,this.$split(a))};this.insertInLine=function(b,a){var c=this.clippedPos(b.row,b.column),e=this.pos(b.row,b.column+a.length);this.applyDelta({start:c,end:e,action:"insert",lines:[a]},!0);return this.clonePos(e)};this.clippedPos=function(b,a){var c=this.getLength();void 0===b?b=c:0>b?b=0:b>=c&&(b=c-1,a=void 0);c=this.getLine(b);void 0==a&&(a=c.length);a=Math.min(Math.max(a,
0),c.length);return{row:b,column:a}};this.clonePos=function(b){return{row:b.row,column:b.column}};this.pos=function(b,a){return{row:b,column:a}};this.$clipPosition=function(b){var a=this.getLength();b.row>=a?(b.row=Math.max(0,a-1),b.column=this.getLine(a-1).length):(b.row=Math.max(0,b.row),b.column=Math.min(Math.max(b.column,0),this.getLine(b.row).length));return b};this.insertFullLines=function(b,a){b=Math.min(Math.max(b,0),this.getLength());var c=0;b<this.getLength()?(a=a.concat([""]),c=0):(a=[""].concat(a),
b--,c=this.$lines[b].length);this.insertMergedLines({row:b,column:c},a)};this.insertMergedLines=function(b,a){var c=this.clippedPos(b.row,b.column),e={row:c.row+a.length-1,column:(1==a.length?c.column:0)+a[a.length-1].length};this.applyDelta({start:c,end:e,action:"insert",lines:a});return this.clonePos(e)};this.remove=function(b){var a=this.clippedPos(b.start.row,b.start.column);b=this.clippedPos(b.end.row,b.end.column);this.applyDelta({start:a,end:b,action:"remove",lines:this.getLinesForRange({start:a,
end:b})});return this.clonePos(a)};this.removeInLine=function(a,c,e){c=this.clippedPos(a,c);a=this.clippedPos(a,e);this.applyDelta({start:c,end:a,action:"remove",lines:this.getLinesForRange({start:c,end:a})},!0);return this.clonePos(c)};this.removeFullLines=function(a,c){a=Math.min(Math.max(0,a),this.getLength()-1);c=Math.min(Math.max(0,c),this.getLength()-1);var f=c==this.getLength()-1&&0<a,d=c<this.getLength()-1,g=f?a-1:a,f=f?this.getLine(g).length:0,h=d?c+1:c,d=d?0:this.getLine(h).length,g=new e(g,
f,h,d),d=this.$lines.slice(a,c+1);this.applyDelta({start:g.start,end:g.end,action:"remove",lines:this.getLinesForRange(g)});return d};this.removeNewLine=function(a){a<this.getLength()-1&&0<=a&&this.applyDelta({start:this.pos(a,this.getLine(a).length),end:this.pos(a+1,0),action:"remove",lines:["",""]})};this.replace=function(a,c){!a instanceof e&&(a=e.fromPoints(a.start,a.end));if(0===c.length&&a.isEmpty())return a.start;if(c==this.getTextRange(a))return a.end;this.remove(a);return c?this.insert(a.start,
c):a.start};this.applyDeltas=function(a){for(var c=0;c<a.length;c++)this.applyDelta(a[c])};this.revertDeltas=function(a){for(var c=a.length-1;0<=c;c--)this.revertDelta(a[c])};this.applyDelta=function(b,c){var f="insert"==b.action;(f?1>=b.lines.length&&!b.lines[0]:!e.comparePoints(b.start,b.end))||(f&&2E4<b.lines.length&&this.$splitAndapplyLargeDelta(b,2E4),a(this.$lines,b,c),this._signal("change",b))};this.$splitAndapplyLargeDelta=function(a,c){var e=a.lines,f=e.length,d=a.start.row,g=a.start.column,
m=0,h=0;do{var m=h,h=h+(c-1),n=e.slice(m,h);if(h>f){a.lines=n;a.start.row=d+m;a.start.column=g;break}n.push("");this.applyDelta({start:this.pos(d+m,g),end:this.pos(d+h,g=0),action:a.action,lines:n},!0)}while(1)};this.revertDelta=function(a){this.applyDelta({start:this.clonePos(a.start),end:this.clonePos(a.end),action:"insert"==a.action?"remove":"insert",lines:a.lines.slice()})};this.indexToPosition=function(a,c){for(var e=this.$lines||this.getAllLines(),f=this.getNewLineCharacter().length,d=c||0,
g=e.length;d<g;d++)if(a-=e[d].length+f,0>a)return{row:d,column:a+e[d].length+f};return{row:g-1,column:e[g-1].length}};this.positionToIndex=function(a,c){for(var e=this.$lines||this.getAllLines(),f=this.getNewLineCharacter().length,d=0,g=Math.min(a.row,e.length),m=c||0;m<g;++m)d+=e[m].length+f;return d+a.column}}).call(d.prototype);h.Document=d});
define("ace/lib/lang",["require","exports","module"],function(d,h,l){h.last=function(a){return a[a.length-1]};h.stringReverse=function(a){return a.split("").reverse().join("")};h.stringRepeat=function(a,e){for(var f="";0<e;)if(e&1&&(f+=a),e>>=1)a+=a;return f};var g=/^\s\s*/,a=/\s\s*$/;h.stringTrimLeft=function(a){return a.replace(g,"")};h.stringTrimRight=function(c){return c.replace(a,"")};h.copyObject=function(a){var e={},f;for(f in a)e[f]=a[f];return e};h.copyArray=function(a){for(var e=[],f=0,
b=a.length;f<b;f++)e[f]=a[f]&&"object"==typeof a[f]?this.copyObject(a[f]):a[f];return e};h.deepCopy=function e(a){if("object"!==typeof a||!a)return a;var b;if(Array.isArray(a)){b=[];for(var d=0;d<a.length;d++)b[d]=e(a[d]);return b}b=a.constructor;if(b===RegExp)return a;b=b();for(d in a)b[d]=e(a[d]);return b};h.arrayToMap=function(a){for(var d={},b=0;b<a.length;b++)d[a[b]]=1;return d};h.createMap=function(a){var d=Object.create(null),b;for(b in a)d[b]=a[b];return d};h.arrayRemove=function(a,d){for(var b=
0;b<=a.length;b++)d===a[b]&&a.splice(b,1)};h.escapeRegExp=function(a){return a.replace(/([.*+?^${}()|[\]\/\\])/g,"\\$1")};h.escapeHTML=function(a){return a.replace(/&/g,"&#38;").replace(/"/g,"&#34;").replace(/'/g,"&#39;").replace(/</g,"&#60;")};h.getMatchOffsets=function(a,d){var b=[];a.replace(d,function(a){b.push({offset:arguments[arguments.length-2],length:a.length})});return b};h.deferredCall=function(a){var d=null,b=function(){d=null;a()},g=function(a){g.cancel();d=setTimeout(b,a||0);return g};
g.schedule=g;g.call=function(){this.cancel();a();return g};g.cancel=function(){clearTimeout(d);d=null;return g};g.isPending=function(){return d};return g};h.delayedCall=function(a,d){var b=null,g=function(){b=null;a()},h=function(a){null==b&&(b=setTimeout(g,a||d))};h.delay=function(a){b&&clearTimeout(b);b=setTimeout(g,a||d)};h.schedule=h;h.call=function(){this.cancel();a()};h.cancel=function(){b&&clearTimeout(b);b=null};h.isPending=function(){return b};return h}});
define("ace/worker/mirror","require exports module ace/range ace/document ace/lib/lang".split(" "),function(d,h,l){d("../range");var g=d("../document").Document,a=d("../lib/lang");d=h.Mirror=function(c){this.sender=c;var d=this.doc=new g(""),f=this.deferredUpdate=a.delayedCall(this.onUpdate.bind(this)),b=this;c.on("change",function(a){a=a.data;if(a[0].start)d.applyDeltas(a);else for(var c=0;c<a.length;c+=2){var g=Array.isArray(a[c+1])?{action:"insert",start:a[c],lines:a[c+1]}:{action:"remove",start:a[c],
end:a[c+1]};d.applyDelta(g,!0)}if(b.$timeout)return f.schedule(b.$timeout);b.onUpdate()})};(function(){this.$timeout=500;this.setTimeout=function(a){this.$timeout=a};this.setValue=function(a){this.doc.setValue(a);this.deferredUpdate.schedule(this.$timeout)};this.getValue=function(a){this.sender.callback(this.doc.getValue(),a)};this.onUpdate=function(){};this.isPending=function(){return this.deferredUpdate.isPending()}}).call(d.prototype)});
define("ace/mode/json/json_parse",["require","exports","module"],function(d,h,l){var g,a,c={'"':'"',"\\":"\\","/":"/",b:"\b",f:"\f",n:"\n",r:"\r",t:"\t"},e,f=function(a){throw{name:"SyntaxError",message:a,at:g,text:e};},b=function(b){b&&b!==a&&f("Expected '"+b+"' instead of '"+a+"'");a=e.charAt(g);g+=1;return a},k=function(){var c;c="";"-"===a&&(c="-",b("-"));for(;"0"<=a&&"9">=a;)c+=a,b();if("."===a)for(c+=".";b()&&"0"<=a&&"9">=a;)c+=a;if("e"===a||"E"===a){c+=a;b();if("-"===a||"+"===a)c+=a,b();for(;"0"<=
a&&"9">=a;)c+=a,b()}c=+c;if(isNaN(c))f("Bad number");else return c},t=function(){var d,e,g="",h;if('"'===a)for(;b();){if('"'===a)return b(),g;if("\\"===a)if(b(),"u"===a){for(e=h=0;4>e;e+=1){d=parseInt(b(),16);if(!isFinite(d))break;h=16*h+d}g+=String.fromCharCode(h)}else if("string"===typeof c[a])g+=c[a];else break;else g+=a}f("Bad string")},p=function(){for(;a&&" ">=a;)b()},u=function(){switch(a){case "t":return b("t"),b("r"),b("u"),b("e"),!0;case "f":return b("f"),b("a"),b("l"),b("s"),b("e"),!1;
case "n":return b("n"),b("u"),b("l"),b("l"),null}f("Unexpected '"+a+"'")},s;s=function(){p();switch(a){case "{":var c;a:{var d={};if("{"===a){b("{");p();if("}"===a){b("}");c=d;break a}for(;a;){c=t();p();b(":");Object.hasOwnProperty.call(d,c)&&f('Duplicate key "'+c+'"');d[c]=s();p();if("}"===a){b("}");c=d;break a}b(",");p()}}f("Bad object");c=void 0}return c;case "[":a:{c=[];if("["===a){b("[");p();if("]"===a){b("]");break a}for(;a;){c.push(s());p();if("]"===a){b("]");break a}b(",");p()}}f("Bad array");
c=void 0}return c;case '"':return t();case "-":return k();default:return"0"<=a&&"9">=a?k():u()}};return function(b,c){var d;e=b;g=0;a=" ";d=s();p();a&&f("Syntax error");return"function"===typeof c?function v(a,b){var d,e,f=a[b];if(f&&"object"===typeof f)for(d in f)Object.hasOwnProperty.call(f,d)&&(e=v(f,d),void 0!==e?f[d]=e:delete f[d]);return c.call(a,b,f)}({"":d},""):d}});
define("ace/mode/json_worker","require exports module ace/lib/oop ace/worker/mirror ace/mode/json/json_parse".split(" "),function(d,h,l){l=d("../lib/oop");var g=d("../worker/mirror").Mirror,a=d("./json/json_parse");d=h.JsonWorker=function(a){g.call(this,a);this.setTimeout(200)};l.inherits(d,g);(function(){this.onUpdate=function(){var c=this.doc.getValue(),d=[];try{c&&a(c)}catch(f){c=this.doc.indexToPosition(f.at-1),d.push({row:c.row,column:c.column,text:f.message,type:"error"})}this.sender.emit("annotate",
d)}}).call(d.prototype)});
define("ace/lib/es5-shim",["require","exports","module"],function(d,h,l){function g(){}function a(a){try{return Object.defineProperty(a,"sentinel",{}),"sentinel"in a}catch(b){}}function c(a){a=+a;a!==a?a=0:0!==a&&a!==1/0&&a!==-(1/0)&&(a=(0<a||-1)*Math.floor(Math.abs(a)));return a}Function.prototype.bind||(Function.prototype.bind=function(a){var b=this;if("function"!=typeof b)throw new TypeError("Function.prototype.bind called on incompatible "+b);var c=f.call(arguments,1),d=function(){if(this instanceof
d){var e=b.apply(this,c.concat(f.call(arguments)));return Object(e)===e?e:this}return b.apply(a,c.concat(f.call(arguments)))};b.prototype&&(g.prototype=b.prototype,d.prototype=new g,g.prototype=null);return d});d=Function.prototype.call;var e=Object.prototype,f=Array.prototype.slice,b=d.bind(e.toString),k=d.bind(e.hasOwnProperty),t,p,u,s,m;if(m=k(e,"__defineGetter__"))t=d.bind(e.__defineGetter__),p=d.bind(e.__defineSetter__),u=d.bind(e.__lookupGetter__),s=d.bind(e.__lookupSetter__);if(2!=[1,2].splice(0).length)if(function(){function a(b){b=
Array(b+2);b[0]=b[1]=0;return b}var b=[],c;b.splice.apply(b,a(20));b.splice.apply(b,a(26));c=b.length;b.splice(5,0,"XXX");c+1==b.length;if(c+1==b.length)return!0}()){var z=Array.prototype.splice;Array.prototype.splice=function(a,b){return arguments.length?z.apply(this,[void 0===a?0:a,void 0===b?this.length-a:b].concat(f.call(arguments,2))):[]}}else Array.prototype.splice=function(a,b){var c=this.length;0<a?a>c&&(a=c):void 0==a?a=0:0>a&&(a=Math.max(c+a,0));a+b<c||(b=c-a);var d=this.slice(a,a+b),e=
f.call(arguments,2),g=e.length;if(a===c)g&&this.push.apply(this,e);else{var h=Math.min(b,c-a),k=a+h,l=k+g-h,m=c-k,c=c-h;if(l<k)for(h=0;h<m;++h)this[l+h]=this[k+h];else if(l>k)for(h=m;h--;)this[l+h]=this[k+h];if(g&&a===c)this.length=c,this.push.apply(this,e);else for(this.length=c+g,h=0;h<g;++h)this[a+h]=e[h]}return d};Array.isArray||(Array.isArray=function(a){return"[object Array]"==b(a)});d=Object("a");var n="a"!=d[0]||!(0 in d);Array.prototype.forEach||(Array.prototype.forEach=function(a,c){var d=
r(this),e=n&&"[object String]"==b(this)?this.split(""):d,f=-1,g=e.length>>>0;if("[object Function]"!=b(a))throw new TypeError;for(;++f<g;)f in e&&a.call(c,e[f],f,d)});Array.prototype.map||(Array.prototype.map=function(a,c){var d=r(this),e=n&&"[object String]"==b(this)?this.split(""):d,f=e.length>>>0,g=Array(f);if("[object Function]"!=b(a))throw new TypeError(a+" is not a function");for(var h=0;h<f;h++)h in e&&(g[h]=a.call(c,e[h],h,d));return g});Array.prototype.filter||(Array.prototype.filter=function(a,
c){var d=r(this),e=n&&"[object String]"==b(this)?this.split(""):d,f=e.length>>>0,g=[],h;if("[object Function]"!=b(a))throw new TypeError(a+" is not a function");for(var k=0;k<f;k++)k in e&&(h=e[k],a.call(c,h,k,d)&&g.push(h));return g});Array.prototype.every||(Array.prototype.every=function(a,c){var d=r(this),e=n&&"[object String]"==b(this)?this.split(""):d,f=e.length>>>0;if("[object Function]"!=b(a))throw new TypeError(a+" is not a function");for(var g=0;g<f;g++)if(g in e&&!a.call(c,e[g],g,d))return!1;
return!0});Array.prototype.some||(Array.prototype.some=function(a,c){var d=r(this),e=n&&"[object String]"==b(this)?this.split(""):d,f=e.length>>>0;if("[object Function]"!=b(a))throw new TypeError(a+" is not a function");for(var g=0;g<f;g++)if(g in e&&a.call(c,e[g],g,d))return!0;return!1});Array.prototype.reduce||(Array.prototype.reduce=function(a){var c=r(this),d=n&&"[object String]"==b(this)?this.split(""):c,e=d.length>>>0;if("[object Function]"!=b(a))throw new TypeError(a+" is not a function");
if(!e&&1==arguments.length)throw new TypeError("reduce of empty array with no initial value");var f=0,g;if(2<=arguments.length)g=arguments[1];else{do{if(f in d){g=d[f++];break}if(++f>=e)throw new TypeError("reduce of empty array with no initial value");}while(1)}for(;f<e;f++)f in d&&(g=a.call(void 0,g,d[f],f,c));return g});Array.prototype.reduceRight||(Array.prototype.reduceRight=function(a){var c=r(this),d=n&&"[object String]"==b(this)?this.split(""):c,e=d.length>>>0;if("[object Function]"!=b(a))throw new TypeError(a+
" is not a function");if(!e&&1==arguments.length)throw new TypeError("reduceRight of empty array with no initial value");var f,e=e-1;if(2<=arguments.length)f=arguments[1];else{do{if(e in d){f=d[e--];break}if(0>--e)throw new TypeError("reduceRight of empty array with no initial value");}while(1)}do e in this&&(f=a.call(void 0,f,d[e],e,c));while(e--);return f});Array.prototype.indexOf&&-1==[0,1].indexOf(1,2)||(Array.prototype.indexOf=function(a){var d=n&&"[object String]"==b(this)?this.split(""):r(this),
e=d.length>>>0;if(!e)return-1;var f=0;1<arguments.length&&(f=c(arguments[1]));for(f=0<=f?f:Math.max(0,e+f);f<e;f++)if(f in d&&d[f]===a)return f;return-1});Array.prototype.lastIndexOf&&-1==[0,1].lastIndexOf(0,-3)||(Array.prototype.lastIndexOf=function(a){var d=n&&"[object String]"==b(this)?this.split(""):r(this),e=d.length>>>0;if(!e)return-1;var f=e-1;1<arguments.length&&(f=Math.min(f,c(arguments[1])));for(f=0<=f?f:e-Math.abs(f);0<=f;f--)if(f in d&&a===d[f])return f;return-1});Object.getPrototypeOf||
(Object.getPrototypeOf=function(a){return a.__proto__||(a.constructor?a.constructor.prototype:e)});Object.getOwnPropertyDescriptor||(Object.getOwnPropertyDescriptor=function(a,b){if("object"!=typeof a&&"function"!=typeof a||null===a)throw new TypeError("Object.getOwnPropertyDescriptor called on a non-object: "+a);if(k(a,b)){var c,d,f;c={enumerable:!0,configurable:!0};if(m){var g=a.__proto__;a.__proto__=e;d=u(a,b);f=s(a,b);a.__proto__=g;if(d||f)return d&&(c.get=d),f&&(c.set=f),c}c.value=a[b];return c}});
Object.getOwnPropertyNames||(Object.getOwnPropertyNames=function(a){return Object.keys(a)});if(!Object.create){var w;w=null===Object.prototype.__proto__?function(){return{__proto__:null}}:function(){var a={},b;for(b in a)a[b]=null;a.constructor=a.hasOwnProperty=a.propertyIsEnumerable=a.isPrototypeOf=a.toLocaleString=a.toString=a.valueOf=a.__proto__=null;return a};Object.create=function(a,b){var c;if(null===a)c=w();else{if("object"!=typeof a)throw new TypeError("typeof prototype["+typeof a+"] != 'object'");
c=function(){};c.prototype=a;c=new c;c.__proto__=a}void 0!==b&&Object.defineProperties(c,b);return c}}if(Object.defineProperty&&(d=a({}),h="undefined"==typeof document||a(document.createElement("div")),!d||!h))var v=Object.defineProperty;if(!Object.defineProperty||v)Object.defineProperty=function(a,b,c){if("object"!=typeof a&&"function"!=typeof a||null===a)throw new TypeError("Object.defineProperty called on non-object: "+a);if("object"!=typeof c&&"function"!=typeof c||null===c)throw new TypeError("Property description must be an object: "+
c);if(v)try{return v.call(Object,a,b,c)}catch(d){}if(k(c,"value"))if(m&&(u(a,b)||s(a,b))){var f=a.__proto__;a.__proto__=e;delete a[b];a[b]=c.value;a.__proto__=f}else a[b]=c.value;else{if(!m)throw new TypeError("getters & setters can not be defined on this javascript engine");k(c,"get")&&t(a,b,c.get);k(c,"set")&&p(a,b,c.set)}return a};Object.defineProperties||(Object.defineProperties=function(a,b){for(var c in b)k(b,c)&&Object.defineProperty(a,c,b[c]);return a});Object.seal||(Object.seal=function(a){return a});
Object.freeze||(Object.freeze=function(a){return a});try{Object.freeze(function(){})}catch(D){Object.freeze=function(a){return function(b){return"function"==typeof b?b:a(b)}}(Object.freeze)}Object.preventExtensions||(Object.preventExtensions=function(a){return a});Object.isSealed||(Object.isSealed=function(a){return!1});Object.isFrozen||(Object.isFrozen=function(a){return!1});Object.isExtensible||(Object.isExtensible=function(a){if(Object(a)===a)throw new TypeError;for(var b="";k(a,b);)b+="?";a[b]=
!0;var c=k(a,b);delete a[b];return c});if(!Object.keys){var x=!0,y="toString toLocaleString valueOf hasOwnProperty isPrototypeOf propertyIsEnumerable constructor".split(" "),A=y.length,q;for(q in{toString:null})x=!1;Object.keys=function(a){if("object"!=typeof a&&"function"!=typeof a||null===a)throw new TypeError("Object.keys called on a non-object");var b=[],c;for(c in a)k(a,c)&&b.push(c);if(x)for(c=0;c<A;c++){var d=y[c];k(a,d)&&b.push(d)}return b}}Date.now||(Date.now=function(){return(new Date).getTime()});
q="\t\n\x0B\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000\u2028\u2029\ufeff";if(!String.prototype.trim||q.trim()){q="["+q+"]";var B=new RegExp("^"+q+q+"*"),C=new RegExp(q+q+"*$");String.prototype.trim=function(){return String(this).replace(B,"").replace(C,"")}}var r=function(a){if(null==a)throw new TypeError("can't convert "+a+" to object");return Object(a)}});
